import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createState,persistState,loadState,exportState,importState,SAVE_KEY} from '../src/save.js';
import {scheduleReview,reviewFromAnswer} from '../src/reviews.js';
import {masteryValue,updateMastery} from '../src/mastery.js';
import {currentStreak,profileLevel} from '../src/gamification.js';
import {gradeAnswer,createSession,recordAnswer,pickNextQuestion,finishSession,matchesQuestion} from '../src/training.js';
import {studyStats} from '../src/statistics.js';
import {diagramSVG} from '../src/components.js';
import {PHYSICS_AREA_ORDER} from '../src/config.js';
const bank=JSON.parse(fs.readFileSync(new URL('../content/bank.json',import.meta.url),'utf8'));
const curriculum=JSON.parse(fs.readFileSync(new URL('../content/curriculum.json',import.meta.url),'utf8'));
const now=new Date(2026,8,6,12).getTime(),day=86400000;
const memory=()=>{const items=new Map();return {getItem:k=>items.get(k)??null,setItem:(k,v)=>items.set(k,v)};};
test('migração preserva Biologia e incorpora os lotes de Física sem IDs duplicados',()=>{assert.equal(bank.questions.length,3384);assert.equal(bank.questions.filter(q=>q.discipline==='biologia').length,50);assert.equal(bank.questions.filter(q=>q.contentTrack==='fisica-l1-batch-01').length,20);assert.equal(bank.questions.filter(q=>q.contentTrack==='physics-licensed-complete').length,3314);assert.equal(bank.questions.filter(q=>q.contentTrack==='physics-licensed-complete'&&!q.needsReview).length,538);assert.equal(bank.questions.filter(q=>q.needsReview).length,2776);assert.equal(new Set(bank.questions.map(q=>q.id)).size,3384);assert.equal(new Set(bank.concepts.map(c=>c.discipline)).size,13);assert.equal(bank.concepts.filter(c=>c.flashcard).length,188);for(const c of bank.concepts)for(const id of c.officialIds)assert.ok(curriculum.objects.some(o=>o.id===id));for(const q of bank.questions){assert.ok(gradeAnswer(q,q.answer),q.id);if(q.type==='choice'){assert.ok(q.options.length>=4);if(!q.needsReview)assert.equal(new Set(q.options).size,q.options.length);}assert.ok(q.explanation.length>40);}});
test('perfil e todo o progresso sobrevivem ao salvamento e à exportação',()=>{const s=createState(),m=memory();s.profile={name:'Vitória',goal:'USP'};persistState(s,m);assert.equal(loadState(m).state.profile.name,'Vitória');assert.deepEqual(importState(exportState(s)),s);assert.throws(()=>importState('{"app":"outro"}'));m.setItem(SAVE_KEY,'broken');assert.equal(loadState(m).blocked,true);});
test('backup anterior recupera arquivo corrompido',()=>{const s=createState(),m=memory();s.profile={name:'Ana'};persistState(s,m);s.xp=10;persistState(s,m);m.setItem(SAVE_KEY,'{');const r=loadState(m);assert.equal(r.state.profile.name,'Ana');assert.ok(r.warning);});
test('acerto e erro registram XP, domínio, confiança, revisão e estatísticas',()=>{const s=createState(),q=bank.questions[0],session=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,session,q,q.answer,'sure',40,now);assert.ok(s.xp>0);assert.ok(masteryValue(s.concepts[q.conceptId],null,now)>0);const q2=bank.questions.find(x=>x.conceptId===q.conceptId&&x.id!==q.id);session.feedback=null;recordAnswer(s,bank,session,q2,'resposta errada','sure',30,now+50000);assert.equal(s.errors[q2.id].falseConfidence,true);assert.equal(s.reviews[q.conceptId].dueAt,now+50000+600000);assert.equal(studyStats(s,bank.concepts,now).wrong,1);assert.equal(currentStreak(s.activity,now),1);});
test('responder novamente não multiplica XP e fechar sessão é idempotente',()=>{const s=createState(),q=bank.questions[0];let a=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,a,q,q.answer,'sure',30,now);const xp=s.xp;assert.equal(recordAnswer(s,bank,a,q,q.answer,'sure',30,now),null);a=createSession(s,bank,'practice',{},now+100000);recordAnswer(s,bank,a,q,q.answer,'sure',30,now+100000);assert.equal(s.xp,xp);finishSession(s,a,now+200000);finishSession(s,a,now+200000);assert.equal(s.sessions.length,1);});
test('chutes nunca constroem domínio alto; variedade e dias são necessários',()=>{const q=bank.questions[0];const sure=updateMastery(null,q,true,'sure',30,now),guess=updateMastery(null,q,true,'guess',30,now);assert.ok(sure.score>guess.score);let c=null;for(let i=0;i<30;i++)c=updateMastery(c,{...q,id:'var-'+i},true,'guess',30,now+i*day);assert.ok(c.score<=35);assert.ok(masteryValue(sure,null,now+90*day)<sure.score);});
test('repetição espaçada reduz esquecimentos e amplia acertos consistentes',()=>{const a=scheduleReview(null,'good',now),b=scheduleReview(a,'good',a.dueAt),c=scheduleReview(b,'easy',b.dueAt),d=scheduleReview(c,'forgot',c.dueAt);assert.equal(a.interval,1);assert.equal(b.interval,3);assert.ok(c.interval>b.interval);assert.equal(d.dueAt-c.dueAt,600000);assert.equal(d.repetitions,0);});
test('sequência usa dias de calendário e tolera hoje ainda não estudado',()=>{const activity={'2026-09-04':{answers:1,reviews:0},'2026-09-05':{answers:0,reviews:1}};assert.equal(currentStreak(activity,now),2);assert.equal(currentStreak(activity,now+day),0);assert.equal(profileLevel(100).level,2);});
test('seleção evita repetir enunciado errado quando há outra variação e obedece filtro',()=>{const s=createState(),q=bank.questions[0],c=bank.concepts.find(c=>c.id===q.conceptId),a=createSession(s,bank,'practice',{subtopic:c.id},now);recordAnswer(s,bank,a,q,'errada','sure',40,now);a.items=[q.id];const next=pickNextQuestion(s,bank,a,now+1000);assert.notEqual(next.id,q.id);assert.equal(next.conceptId,c.id);assert.equal(matchesQuestion(q,c,{discipline:'quimica'},s,now),c.discipline==='quimica');});
test('sobrevivência perde três vidas e relâmpago não aceita resposta após prazo',()=>{const s=createState(),a=createSession(s,bank,'survival',{},now);for(const q of bank.questions.slice(0,3)){a.feedback=null;recordAnswer(s,bank,a,q,'errada','guess',2,now+1000);}assert.equal(a.lives,0);finishSession(s,a,now+3000);assert.equal(s.records.survival,0);const b=createSession(s,bank,'lightning',{},now);assert.equal(recordAnswer(s,bank,b,bank.questions[0],bank.questions[0].answer,'sure',2,now+60000),null);});
test('formatos aceitam vírgula decimal, acentos e sequências, sem vazio igual a zero',()=>{assert.equal(gradeAnswer({type:'numeric',answer:1.5},'1,5'),true);assert.equal(gradeAnswer({type:'numeric',answer:0},''),false);assert.equal(gradeAnswer({type:'text',answer:'mitocôndria'},'Mitocondria'),true);assert.equal(gradeAnswer({type:'order',answer:[2,0,1]},[2,1,0]),false);});

test('chute antecipa revisão distante sem apagar a recompensa diária do cartão',()=>{const previous={...scheduleReview(null,'easy',now),interval:90,dueAt:now+90*day,flashRewardAt:now};const uncertain=reviewFromAnswer(previous,true,'guess',now+1000);assert.ok(uncertain.dueAt<=now+1000+day);assert.equal(uncertain.flashRewardAt,now);const failed=reviewFromAnswer(previous,false,'sure',now+1000);assert.equal(failed.flashRewardAt,now);});

test('backup incompleto é rejeitado antes de substituir progresso válido',()=>{const s=createState(),q=bank.questions[0],a=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,a,q,q.answer,'sure',30,now);assert.deepEqual(importState(exportState(s)),s);delete s.concepts[q.conceptId].attempts;assert.throws(()=>importState(exportState(s)),/domínio/);const broken=createState();broken.activeSession={...a,phase:'invalid'};assert.throws(()=>importState(exportState(broken)),/Sessão/);});

test('falso domínio recebe prioridade no treino de fraquezas com outra variação',()=>{const s=createState(),q=bank.questions[0],other=bank.questions.find(x=>x.conceptId!==q.conceptId);let a=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,a,q,-1,'sure',20,now);a=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,a,other,-1,'guess',20,now);const weak=createSession(s,bank,'weak',{},now);const next=pickNextQuestion(s,bank,weak,now+1000);assert.equal(next.conceptId,q.conceptId);assert.notEqual(next.id,q.id);});

test('questão em needsReview não aparece no treino nem altera domínio ou confiança',()=>{const s=createState(),base=bank.questions[0],q={...base,id:'pending-review',needsReview:true};const c=bank.concepts.find(c=>c.id===q.conceptId),a=createSession(s,{...bank,questions:[q]},'practice',{},now);assert.equal(matchesQuestion(q,c,{},s,now),false);assert.equal(recordAnswer(s,{...bank,questions:[q]},a,q,q.answer,'sure',20,now),null);assert.equal(s.history.length,0);assert.equal(s.concepts[q.conceptId],undefined);});

test('Física usa somente as oito áreas FIXOU e preserva todas as questões',()=>{const qs=bank.questions.filter(q=>q.discipline==='fisica');assert.equal(qs.length,3334);assert.equal(new Set(qs.map(q=>q.id)).size,3334);assert.deepEqual([...new Set(qs.map(q=>q.topic))].sort(),[...PHYSICS_AREA_ORDER].sort());for(const q of qs)assert.doesNotMatch(q.topic+' '+q.subtopic,/Física L[1-4]|Frente [1-3]|Capítulo \d/i);});

test('diagramas autorais de Física são renderizados com descrição acessível',()=>{const motion=diagramSVG({type:'motion-line'}),graph=diagramSVG({type:'velocity-graph'});assert.match(motion,/sessenta metros/);assert.match(graph,/Gráfico de velocidade/);assert.match(graph,/class="diagram-area"/);});

test('banco ativo e histórico continuam válidos após importar',()=>{const s=createState(),publishable=bank.questions.filter(q=>!q.needsReview);for(const q of publishable){const a=createSession(s,bank,'practice',{},now);recordAnswer(s,bank,a,q,q.answer,'think',25,now);finishSession(s,a,now+25000);}const restored=importState(exportState(s));assert.equal(restored.history.length,publishable.length);assert.equal(studyStats(restored,bank.concepts,now).accuracy,100);});
