import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
execFileSync(process.execPath,[path.join(root,'scripts/validate-bank.mjs')],{stdio:'inherit'});
const bank=JSON.parse(read('content/bank.json')),curriculum=JSON.parse(read('content/curriculum.json')),books=JSON.parse(read('content/books.json'));
const tracks={biologia:bank.questions.filter(q=>q.contentTrack==='biologia-foco').length,geometriaPlana:bank.questions.filter(q=>q.contentTrack==='geometria-plana').length,fisicaFoco:bank.questions.filter(q=>q.contentTrack==='fisica-foco').length,geomorfologia:bank.questions.filter(q=>q.contentTrack==='geomorfologia').length};
if(bank.questions.length<300||new Set(bank.questions.map(q=>q.id)).size!==bank.questions.length||tracks.biologia<40||tracks.geometriaPlana<70||tracks.fisicaFoco<50||tracks.geomorfologia<50)throw new Error('O banco complementar não atingiu os mínimos de conteúdo.');
for(const c of bank.concepts)if(!c.officialIds.every(id=>curriculum.objects.some(o=>o.id===id)))throw new Error('Origem curricular inválida: '+c.id);
const catalog=`export const BANK=${JSON.stringify(bank)};\nexport const CURRICULUM=${JSON.stringify(curriculum)};\nexport const BOOKS=${JSON.stringify(books)};\n`;
fs.writeFileSync(path.join(root,'src/catalog.js'),catalog);
const files=['src/catalog.js','src/config.js','src/utils.js','src/save.js','src/reviews.js','src/mastery.js','src/gamification.js','src/statistics.js','src/training.js','src/components.js','src/screens.js','src/screens-library.js','src/screens-profile.js','src/screens-settings.js','src/session-view.js','src/controller.js','src/main.js'];
const code=files.map(f=>read(f).replace(/^import\s+.*?;\s*$/gm,'').replace(/^export\s+/gm,'')).join('\n');
const bundle=`(()=>{'use strict';\n${code}\n})();`;new vm.Script(bundle,{filename:'fuvest-mastery.js'});
const css=read('styles/app.css');const html=read('index.html').replace('<link rel="stylesheet" href="styles/app.css">',()=>`<style>${css}</style>`).replace('<script type="module" src="src/main.js"></script>',()=>`<script>${bundle.replace(/<\/script/gi,'<\\/script')}</script>`);
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/index.html'),html);
fs.mkdirSync(path.join(root,'dist/assets'),{recursive:true});fs.copyFileSync(path.join(root,'assets/fixou-logo.png'),path.join(root,'dist/assets/fixou-logo.png'));
console.log('Build OK · '+bank.questions.length+' questões · '+bank.concepts.length+' conceitos · '+curriculum.objects.length+' registros curriculares · '+Math.round(Buffer.byteLength(html)/1024)+' KB');
