import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const file=path.join(root,'content/bank.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8'));
if(bank.questions.some(q=>q.contentTrack==='biologia-foco')){console.log('Banco complementar já foi aplicado; nada a duplicar.');process.exit(0);}
const existing=new Set(bank.concepts.map(c=>c.id));
const original='Questão original — estilo FUVEST';
const ids={bio:['of-260','of-261','of-262','of-263','of-266','of-268','of-269','of-270','of-271','of-272','of-273'],math:['of-175','of-176','of-177','of-178','of-179','of-180','of-181','of-182','of-183'],fis:['of-199','of-200','of-201','of-202','of-241','of-242','of-243'],geo:['of-322','of-323','of-324','of-325','of-326','of-334','of-347','of-348','of-349','of-350']};
const rotate=(items,n)=>items.map((_,i)=>items[(i+n)%items.length]);
const makeChoice=(spec,index,kind)=>{
 const answer=index%5, options=rotate([spec.correct,...spec.wrong],answer);
 const prompt=kind===1?`Em relação a ${spec.subtopic}, qual afirmação está correta? ${spec.context||''}`:`Em uma situação ligada a ${spec.subtopic}, qual conclusão é adequada? ${spec.application||''}`;
 return {id:`${spec.id}-${kind}`,conceptId:spec.id,difficulty:spec.difficulty||((index%3)+2),type:'choice',prompt,options,answer,explanation:`${spec.explain} ${kind===2?spec.applicationExplain||spec.explain:''}`,estimatedSeconds:spec.seconds||100,tags:['autoral',...spec.tags||[]],discipline:spec.discipline,topic:spec.topic,subtopic:spec.subtopic,source:original,year:2027,officialIds:spec.officialIds,conceptsTested:[spec.subtopic],contentTrack:spec.track};
};
const addGeneric=(spec,officialIds,track)=>{spec.officialIds=officialIds;spec.track=track;if(existing.has(spec.id))throw new Error('ID duplicado '+spec.id);existing.add(spec.id);bank.concepts.push({id:spec.id,discipline:spec.discipline,topic:spec.topic,subtopic:spec.subtopic,officialIds,summary:spec.summary,flashcard:{front:spec.front||`O que revisar em ${spec.subtopic}?`,back:spec.back||spec.summary}});bank.questions.push(makeChoice(spec,bank.concepts.length,1),makeChoice(spec,bank.concepts.length+1,2));};
const bio=(subtopic,summary,correct,wrong,application,applicationExplain,tags=[])=>({id:'bio-extra-'+subtopic.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'),discipline:'biologia',topic:'Evolução e Ecologia',subtopic,summary,correct,wrong,context:'Considere uma população submetida a mudanças ambientais ao longo de gerações.',application,applicationExplain,tags});
[
 bio('Teoria moderna da evolução','A teoria sintética combina seleção natural, genética e mudanças na frequência de alelos.','A seleção atua sobre fenótipos, enquanto a evolução é observada como mudança nas frequências alélicas.',['Indivíduos mudam seus alelos dirigidos pela necessidade.','A seleção cria mutações úteis de modo intencional.','A evolução ocorre apenas em indivíduos.','Toda característica adquirida é herdada.'],'Uma população pode adaptar sua composição genética quando fenótipos herdáveis afetam o sucesso reprodutivo.','A hereditariedade e a reprodução diferencial conectam variação fenotípica à mudança populacional.',['evolução','teoria-sintética']),
 bio('Mutação e recombinação','Mutações originam novos alelos e a recombinação reorganiza alelos; ambas ampliam a variabilidade sobre a qual a seleção pode atuar.','A reprodução sexuada pode gerar combinações novas sem necessariamente criar alelos novos.',['Mutações sempre são vantajosas.','A recombinação elimina toda variação.','A seleção natural produz alelos do zero.','Mutações ocorrem somente quando o ambiente exige.'],'Em uma população, uma nova combinação genética pode aumentar a variação de fenótipos entre descendentes.','A recombinação rearranja material já existente; mutações são a fonte primária de novos alelos.',['evolução','genética']),
 bio('Isolamento reprodutivo e especiação','Barreiras pré-zigóticas ou pós-zigóticas reduzem o fluxo gênico e podem levar à formação de novas espécies.','O isolamento reprodutivo é central para que populações divergentes deixem de trocar genes com sucesso.',['Qualquer diferença de cor já define uma espécie.','A especiação exige que todos os indivíduos se tornem idênticos.','Fluxo gênico intenso acelera sempre a divergência.','Espécies novas surgem em uma única geração por escolha.'],'Duas populações separadas por uma barreira podem acumular diferenças até não produzirem descendentes férteis quando se reencontram.','A interrupção do fluxo gênico permite que seleção, deriva e mutação atuem de modo independente.',['especiação','isolamento']),
 bio('Filogenia e ancestralidade','Cladogramas representam hipóteses de parentesco e grupos monofiléticos reúnem um ancestral e todos os seus descendentes.','O compartilhamento de uma característica derivada pode indicar um ancestral comum mais recente.',['A posição gráfica sempre mede idade absoluta.','Organismos no topo são necessariamente superiores.','Toda semelhança é homologia.','Um cladograma mostra uma escala obrigatória de tamanho corporal.'],'Se dois grupos compartilham uma sinapomorfia, a árvore pode apoiá-los como grupo-irmão.','Características homólogas herdadas de um ancestral comum têm valor filogenético, ao contrário de analogias por convergência.',['filogenia','evidências']),
 bio('Evidências da evolução','Fósseis, anatomia comparada, embriologia, biogeografia e dados moleculares fornecem evidências convergentes da evolução.','Semelhanças de sequência de DNA podem sustentar parentesco evolutivo entre espécies.',['Fósseis provam que espécies atuais nunca mudaram.','Órgãos análogos indicam sempre ancestralidade direta.','A biogeografia não informa evolução.','Evidências precisam ser idênticas para concordar.'],'Uma proteína mais semelhante entre duas espécies tende a indicar maior proximidade evolutiva, se a comparação for adequada.','Múltiplas linhas independentes de evidência fortalecem uma hipótese histórica.',['evolução','evidências']),
 bio('Evolução humana','A evolução humana envolve linhagens ramificadas, ancestralidade comum com outros primatas e mudanças biológicas e culturais.','Humanos e chimpanzés atuais compartilham um ancestral comum, mas um não descende do outro.',['Humanos descendem dos chimpanzés atuais.','A evolução humana foi linear e sem ramificações.','Cultura não influencia a história humana.','Todos os hominínios viveram ao mesmo tempo.'],'Um fóssil pode ser interpretado junto a dados anatômicos, genéticos e arqueológicos.','A história evolutiva humana é uma árvore com divergências e intercâmbio de características, não uma escada.',['evolução-humana']),
 bio('Deriva genética e efeito fundador','A deriva genética altera frequências alélicas por amostragem ao acaso, sendo mais forte em populações pequenas; o efeito fundador é um caso de deriva.','Uma pequena colônia pode ter frequências alélicas diferentes das da população de origem por acaso.',['A deriva sempre aumenta adaptação.','Populações enormes sofrem deriva mais intensa.','O efeito fundador depende de seleção intencional.','A deriva cria alelos novos.'],'Após uma enchente, poucos indivíduos colonizam uma ilha e uma característica rara se torna comum.','A mudança resulta da amostra inicial, não necessariamente de vantagem adaptativa.',['deriva','populações']),
 bio('Fluxo gênico','Migração de indivíduos férteis ou de seus gametas tende a homogeneizar frequências alélicas entre populações.','A entrada de migrantes pode introduzir alelos e reduzir a diferenciação entre populações.',['Fluxo gênico sempre aumenta isolamento.','Migração nunca altera frequências.','Apenas mutações movem alelos entre populações.','Fluxo gênico impede qualquer reprodução.'],'Duas populações conectadas por dispersão frequente tendem a se parecer geneticamente mais do que populações isoladas.','A troca de genes contrasta com a divergência causada por isolamento.',['fluxo-gênico']),
 bio('Seleção natural e resistência','O uso de antibióticos seleciona variantes resistentes já presentes ou surgidas por mutação; não transforma todas as bactérias por necessidade.','A frequência de resistência pode aumentar quando o antibiótico elimina preferencialmente as variantes sensíveis.',['O antibiótico ensina cada bactéria a produzir resistência.','A resistência não é herdável.','A seleção elimina apenas bactérias resistentes.','A frequência nunca muda.'],'Uma população bacteriana exposta repetidamente ao mesmo fármaco pode se tornar menos sensível.','A pressão seletiva altera a composição da população; o tratamento adequado reduz a seleção e a transmissão.',['seleção','resistência']),
 bio('Seleção sexual','Características que aumentam o sucesso de acasalamento podem ser favorecidas mesmo com custo de sobrevivência, configurando seleção sexual.','Uma ornamentação pode se espalhar se aumentar a escolha de parceiros e o ganho reprodutivo.',['Seleção sexual é sinônimo de mutação.','Toda ornamentação aumenta sobrevivência.','Somente fêmeas sofrem seleção.','A seleção sexual não envolve reprodução.'],'Uma cauda chamativa pode ser mantida apesar de elevar o risco de predação.','O balanço entre atração de parceiros e sobrevivência define o resultado seletivo.',['seleção-sexual']),
 bio('Nicho ecológico','O nicho reúne condições, recursos e interações que permitem a uma espécie viver e reproduzir-se; não é apenas o local onde ela mora.','Duas espécies podem compartilhar o habitat e ocupar nichos diferentes.',['Nicho é somente o endereço geográfico.','Habitat e nicho são sempre sinônimos.','Todo nicho é ilimitado.','Espécies não competem por recursos.'],'Se duas aves vivem na mesma árvore mas usam alimentos e horários distintos, a partição reduz a sobreposição de nichos.','A diferenciação de recursos pode diminuir a competição interespecífica.',['ecologia','nicho']),
 bio('Populações e crescimento','Densidade, distribuição, natalidade, mortalidade, imigração e emigração descrevem populações; a capacidade de suporte limita o crescimento.','O crescimento logístico tende a estabilizar próximo da capacidade de suporte.',['Crescimento é sempre exponencial.','Capacidade de suporte independe de recursos.','Densidade não afeta populações.','Mortalidade nunca altera o tamanho populacional.'],'Em um lago com alimento limitado, o aumento da população reduz o crescimento líquido.','Resistência ambiental torna o crescimento dependente da densidade.',['ecologia','populações']),
 bio('Mutualismo, competição e comensalismo','Interações ecológicas podem beneficiar ambos, prejudicar ambos ou beneficiar um sem efeito relevante no outro, conforme o caso.','Mutualismo tem efeito positivo para os dois parceiros, enquanto competição tem efeito negativo para ambos.',['Toda interação é predatória.','Comensalismo prejudica obrigatoriamente os dois.','Mutualismo nunca é obrigatório.','Competição beneficia igualmente os competidores.'],'Uma associação entre micorrizas e raízes pode ampliar a absorção mineral da planta e fornecer compostos ao fungo.','O sinal da interação depende dos efeitos sobre cada participante e do contexto ambiental.',['interações']),
 bio('Predação e cascatas tróficas','Predadores podem alterar abundância e comportamento de presas e produzir efeitos em cascata pela teia alimentar.','A remoção de um predador pode aumentar herbívoros e reduzir a biomassa vegetal.',['Predadores só diminuem biodiversidade.','Cascatas ocorrem sem relações alimentares.','Presas nunca mudam comportamento.','Todo predador ocupa o primeiro nível trófico.'],'A queda de lobos pode liberar cervídeos e intensificar o consumo de plantas em uma paisagem.','Efeitos indiretos propagam-se entre níveis tróficos e podem alterar o ecossistema.',['interações','teias']),
 bio('Cadeias e teias alimentares','Energia entra principalmente pela produção e diminui a cada transferência trófica, enquanto matéria circula.','Uma teia alimentar representa relações múltiplas e não uma única sequência obrigatória.',['Energia é reciclada integralmente.','Consumidores produzem sua própria energia luminosa.','Decompositores não participam dos ciclos.','Toda cadeia tem apenas três níveis.'],'A redução de produtores tende a afetar consumidores de vários níveis conectados.','A conectividade da teia ajuda a explicar efeitos de alterações em uma população.',['ecologia','energia']),
 bio('Biomas mundiais','Clima, solo, latitude e disponibilidade de água condicionam fisionomia e funcionamento de biomas mundiais.','A tundra apresenta baixa temperatura, estação de crescimento curta e vegetação rasteira.',['Floresta tropical é sempre seca e fria.','Desertos recebem chuva abundante o ano inteiro.','Taiga é dominada por gramíneas tropicais.','Tundra possui árvores altas em solo permanentemente descongelado.'],'A latitude e a sazonalidade ajudam a explicar a distribuição de desertos, savanas, florestas temperadas e tundras.','Biomas são padrões ecológicos amplos, não fronteiras políticas rígidas.',['biomas','mundo']),
 bio('Biomas brasileiros','Amazônia, Cerrado, Caatinga, Mata Atlântica, Pantanal e Pampa têm clima, solo, fisionomia e histórias de uso distintas.','O Cerrado possui vegetação adaptada à sazonalidade da chuva e a incêndios naturais, mas é vulnerável à conversão de habitat.',['Caatinga é uma floresta equatorial permanentemente alagada.','Pampa ocorre principalmente na região Norte.','Pantanal não sofre variação sazonal de inundação.','Amazônia é formada apenas por campos abertos.'],'A substituição do Cerrado por monoculturas pode reduzir conectividade e alterar ciclos hídricos.','Conservação depende das características ecológicas e das pressões específicas de cada bioma.',['biomas','brasil']),
 bio('Sucessão ecológica','Sucessão é a mudança temporal da composição de comunidades; pode iniciar em substrato sem solo ou após perturbação que mantém parte do solo.','A sucessão secundária tende a ser mais rápida que a primária porque conserva solo e propágulos.',['Sucessão sempre começa sem organismos.','Comunidades nunca mudam após um distúrbio.','Sucessão é apenas migração.','Toda sucessão termina na mesma comunidade em qualquer clima.'],'Após um incêndio que deixa solo e sementes, espécies pioneiras podem ser substituídas por comunidades mais complexas.','A trajetória depende de condições locais, dispersão e interações.',['ecologia','sucessão']),
 bio('Ciclos da matéria','Carbono, nitrogênio e água circulam entre atmosfera, organismos, solo e corpos d’água por processos biológicos e físicos.','A decomposição devolve elementos ao ambiente e conecta matéria orgânica aos ciclos biogeoquímicos.',['Matéria desaparece ao passar na cadeia.','Nitrogênio atmosférico é usado diretamente por toda planta.','Ciclos não têm reservatórios.','Decompositores interrompem o ciclo.'],'A fixação do nitrogênio transforma uma forma atmosférica em compostos aproveitáveis por outros organismos.','Processos microbianos são essenciais para a disponibilidade de nutrientes.',['ecologia','ciclos']),
 bio('Eutrofização e conservação','Excesso de nutrientes pode causar floração de algas, decomposição intensa e queda do oxigênio dissolvido; conservação combina proteção e manejo.','Reduzir o aporte de nitrogênio e fósforo é uma medida preventiva contra eutrofização cultural.',['Eutrofização aumenta oxigênio indefinidamente.','Conservação depende somente de áreas sem pessoas.','Nutrientes nunca vêm de esgoto.','A biodiversidade não tem valor ecológico.'],'Mata ciliar e tratamento de esgoto podem diminuir o transporte de nutrientes para um lago.','A prevenção atua na fonte do impacto e complementa a recuperação do ecossistema.',['ecologia','conservação'])
].forEach(s=>addGeneric(s,ids.bio,'biologia-foco'));

const geom=(id,subtopic,summary,formula,diagram,questions,officialIds=ids.math)=>({id:'mat-plana-'+id,discipline:'matematica',topic:'Geometria plana',subtopic,summary,front:`Qual ideia central aparece em ${subtopic}?`,back:formula,questions,officialIds,track:'geometria-plana',diagram});
const addGeom=s=>{if(existing.has(s.id))throw new Error('ID duplicado '+s.id);existing.add(s.id);bank.concepts.push({id:s.id,discipline:s.discipline,topic:s.topic,subtopic:s.subtopic,officialIds:s.officialIds,summary:s.summary,flashcard:{front:s.front,back:s.back}});s.questions.forEach((q,i)=>bank.questions.push({...q,id:`${s.id}-${i+1}`,conceptId:s.id,discipline:s.discipline,topic:s.topic,subtopic:s.subtopic,source:original,year:2027,officialIds:s.officialIds,conceptsTested:[s.subtopic],tags:['autoral','geometria-plana'],estimatedSeconds:q.estimatedSeconds||100,difficulty:q.difficulty||((i%3)+2),contentTrack:s.track,diagram:s.diagram}));};
const choice=(prompt,options,answer,explanation)=>({type:'choice',prompt,options,answer,explanation});
[
 geom('area-triangulo','Área do triângulo','A área é base vezes altura dividido por dois.','A=bh/2',{type:'triangle',labels:['b','h']},[choice('Um triângulo tem base 12 cm e altura relativa 7 cm. Qual é sua área?',['19 cm²','42 cm²','84 cm²','96 cm²','168 cm²'],1,'A=12·7/2=42 cm².'),choice('Um terreno triangular tem área 90 m² e base 15 m. Qual é a altura correspondente?',['6 m','9 m','12 m','15 m','18 m'],2,'h=2A/b=180/15=12 m.')]),
 geom('pitagoras','Teorema de Pitágoras','Em triângulo retângulo, o quadrado da hipotenusa é a soma dos quadrados dos catetos.','a²+b²=c²',{type:'right-triangle',labels:['a','b','c']},[choice('Os catetos de um triângulo retângulo medem 6 e 8. A hipotenusa mede',['9','10','12','14','16'],1,'c²=36+64=100, portanto c=10.'),choice('Uma rampa forma triângulo retângulo com altura 5 m e projeção horizontal 12 m. Seu comprimento é',['11 m','12 m','13 m','15 m','17 m'],2,'A hipotenusa é √(5²+12²)=13 m.')]),
 geom('triangulo-equilatero','Área do equilátero','A área do equilátero de lado l é l²√3/4.','A=l²√3/4',{type:'triangle',labels:['l','l','l']},[choice('Use √3≈1,7. Um triângulo equilátero de lado 6 cm tem área aproximada de',['9,0 cm²','12,0 cm²','15,3 cm²','18,0 cm²','30,6 cm²'],2,'A=36·1,7/4=15,3 cm².'),choice('Com √3≈1,7, um equilátero de lado 10 cm tem área aproximada de',['17,0 cm²','25,0 cm²','42,5 cm²','85,0 cm²','170 cm²'],2,'A=100·1,7/4=42,5 cm².')]),
 geom('angulos-triangulo','Soma dos ângulos do triângulo','A soma dos ângulos internos de qualquer triângulo é 180°.','A+B+C=180°',{type:'triangle',labels:['40°','65°','?']},[choice('Dois ângulos de um triângulo medem 40° e 65°. O terceiro mede',['55°','65°','75°','85°','105°'],2,'180−40−65=75°.'),choice('Um triângulo isósceles tem ângulo do vértice 46°. Cada ângulo da base mede',['46°','67°','72°','82°','134°'],1,'Os dois ângulos da base somam 134°, logo cada um mede 67°.')]),
 geom('semelhanca','Semelhança e escala','Em figuras semelhantes, comprimentos variam por k e áreas por k².','A₂/A₁=k²',{type:'similarity',labels:['k','k²']},[choice('Um mapa amplia um triângulo por fator linear 3. A área fica multiplicada por',['3','6','9','12','27'],2,'Áreas escalam por 3²=9.'),choice('Duas figuras semelhantes têm áreas 20 cm² e 180 cm². A razão linear maior/menor é',['3','6','9','18','90'],0,'k²=180/20=9, então k=3.')]),
 geom('teorema-tales','Teorema de Tales','Paralelas cortadas por transversais determinam segmentos proporcionais.','a/b=c/d',{type:'parallel-lines',labels:['a','b','c','d']},[choice('Em duas transversais, segmentos correspondentes medem 4 e 6 numa e 10 e x na outra. x vale',['12','15','18','20','24'],1,'4/6=10/x, então x=15.'),choice('Um feixe de paralelas produz 3/5=9/x. O valor de x é',['10','12','15','18','20'],2,'3x=45, logo x=15.')]),
 geom('trapezio','Área do trapézio','A área é a média das bases multiplicada pela altura.','A=(B+b)h/2',{type:'trapezoid',labels:['B','b','h']},[choice('Bases 14 cm e 8 cm, altura 5 cm. A área é',['22 cm²','35 cm²','45 cm²','55 cm²','70 cm²'],3,'A=(14+8)·5/2=55 cm².'),choice('Um trapézio tem bases 18 m e 10 m e altura 6 m. A área é',['42 m²','56 m²','72 m²','84 m²','108 m²'],3,'A=(18+10)·6/2=84 m².')]),
 geom('paralelogramo','Área do paralelogramo','A base e a altura perpendicular determinam a área.','A=bh',{type:'parallelogram',labels:['b','h']},[choice('Um paralelogramo tem base 13 cm e altura 4 cm. A área é',['17','26','52','68','104'],2,'A=13·4=52 cm².'),choice('A área de um paralelogramo é 96 m² e a base 12 m. A altura é',['6 m','8 m','10 m','12 m','16 m'],1,'h=96/12=8 m.')]),
 geom('losango','Área do losango','A área é metade do produto das diagonais.','A=Dd/2',{type:'rhombus',labels:['D','d']},[choice('Diagonais 10 cm e 6 cm formam losango de área',['16 cm²','30 cm²','60 cm²','80 cm²','120 cm²'],1,'A=10·6/2=30 cm².'),choice('Um losango tem área 84 m² e diagonal maior 14 m. A menor diagonal mede',['6 m','8 m','10 m','12 m','14 m'],1,'d=2A/D=168/14=12 m. A opção D é correta.',3)]),
 geom('deltoide','Área do deltoide','Em um deltoide, a área também pode ser calculada por metade do produto das diagonais.','A=Dd/2',{type:'kite',labels:['D','d']},[choice('As diagonais de um deltoide medem 16 cm e 9 cm. A área é',['36','72','90','144','288'],1,'A=16·9/2=72 cm².'),choice('Um deltoide tem diagonais 20 e 7. Sua área é',['27','50','70','140','280'],2,'A=20·7/2=70 cm².')]),
 geom('retangulo','Perímetro e área do retângulo','Perímetro soma os lados; área multiplica base e altura.','P=2(b+h), A=bh',{type:'rectangle',labels:['b','h']},[choice('Um retângulo 9 cm por 4 cm tem perímetro',['13','18','26','36','52'],2,'P=2(9+4)=26 cm.'),choice('Um retângulo tem área 72 m² e base 8 m. Sua altura é',['6 m','8 m','9 m','12 m','16 m'],2,'h=72/8=9 m.')]),
 geom('quadrado','Diagonal e área do quadrado','A diagonal do quadrado de lado l é l√2 e a área é l².','d=l√2, A=l²',{type:'square',labels:['l','d']},[choice('Um quadrado de lado 7 cm tem área',['14','28','49','56','98'],2,'A=7²=49 cm².'),choice('A diagonal de um quadrado é 10√2 cm. Seu lado mede',['5','10','20','10√2','100'],1,'l=d/√2=10 cm.')]),
 geom('circunferencia','Comprimento da circunferência','O comprimento é 2πr.','C=2πr',{type:'circle',labels:['r']},[choice('Adote π=3. Uma circunferência de raio 5 cm mede',['15','20','30','45','60'],2,'C=2·3·5=30 cm.'),choice('Adote π=3. Um círculo de diâmetro 14 m tem comprimento',['21','28','42','84','196'],2,'C=πd=3·14=42 m.')]),
 geom('circulo-area','Área do círculo','A área é πr².','A=πr²',{type:'circle',labels:['r']},[choice('Adote π=3. Um círculo de raio 4 cm tem área',['12','24','36','48','96'],3,'A=3·16=48 cm².'),choice('Adote π=3. A área de um círculo é 75 cm². Seu raio é',['3','4','5','6','25'],2,'3r²=75, r=5 cm.')]),
 geom('arco','Arco e setor circular','A fração do arco e do setor é a fração do ângulo central em relação a 360°.','L=θ/360·2πr',{type:'sector',labels:['θ','r']},[choice('Em um círculo de raio 6 cm, um arco de 60° mede, com π=3,',['3','6','9','12','18'],1,'L=60/360·2·3·6=6 cm.'),choice('Um setor de 90° tem raio 8 cm. Com π=3, sua área é',['24','32','48','96','192'],2,'A=90/360·3·64=48 cm².')]),
 geom('corda','Corda e distância ao centro','A perpendicular do centro à corda a bisseta; a relação com o raio usa Pitágoras.','(c/2)²+d²=r²',{type:'chord',labels:['r','c','d']},[choice('Raio 5 cm e distância do centro à corda 3 cm. A corda mede',['4','6','8','10','16'],2,'Metade da corda é √(25−9)=4, logo c=8 cm.'),choice('Raio 10 cm e corda 12 cm. A distância do centro à corda é',['4','6','8','10','12'],2,'d=√(100−36)=8 cm.')]),
 geom('tangente','Tangente à circunferência','O raio ao ponto de tangência é perpendicular à tangente.','r⊥tangente',{type:'tangent',labels:['r','90°']},[choice('Se uma reta toca o círculo em T, o ângulo entre OT e a reta tangente é',['0°','45°','60°','90°','180°'],3,'O raio OT é perpendicular à tangente.'),choice('De um ponto externo, dois segmentos tangentes ao mesmo círculo têm comprimentos',['sempre diferentes','iguais','nulos','iguais ao raio','iguais ao diâmetro'],1,'Tangentes traçadas de um mesmo ponto externo têm comprimentos iguais.')]),
 geom('angulo-inscrito','Ângulo inscrito','Um ângulo inscrito mede metade do arco interceptado.','α=arco/2',{type:'circle-angle',labels:['α','2α']},[choice('Um ângulo inscrito intercepta arco de 100°. Ele mede',['25°','40°','50°','100°','200°'],2,'α=100°/2=50°.'),choice('Um ângulo inscrito mede 35°. O arco interceptado mede',['17,5°','35°','70°','105°','140°'],2,'O arco mede o dobro: 70°.')]),
 geom('poligono-soma','Soma dos ângulos do polígono','A soma dos ângulos internos de n-gono é (n−2)·180°.','S=(n−2)180°',{type:'polygon',labels:['n']},[choice('A soma dos ângulos internos de um hexágono é',['360°','540°','720°','900°','1080°'],2,'S=(6−2)·180=720°.'),choice('Um polígono tem soma interna 1260°. Quantos lados possui?',['7','8','9','10','11'],2,'(n−2)180=1260 implica n=9.')]),
 geom('poligono-regular','Ângulo do polígono regular','Em um polígono regular, cada ângulo interno é a soma dividida pelo número de lados.','α=(n−2)180/n',{type:'polygon',labels:['α','n']},[choice('Cada ângulo interno de um octógono regular mede',['90°','120°','135°','140°','150°'],2,'S=1080° e 1080/8=135°.'),choice('Cada ângulo interno de um pentágono regular mede',['72°','90°','108°','120°','144°'],2,'S=540° e 540/5=108°.')]),
 geom('diagonais','Diagonais de polígonos','O número de diagonais de um n-gono é n(n−3)/2.','D=n(n−3)/2',{type:'polygon',labels:['D']},[choice('Um decágono tem quantas diagonais?',['10','20','25','35','45'],3,'D=10·7/2=35.'),choice('Um polígono tem 14 diagonais. Quantos lados tem?',['6','7','8','9','10'],1,'n(n−3)/2=14 dá n=7.')]),
 geom('poligono-regular-apotema','Área do polígono regular','A área é metade do produto do perímetro pelo apótema.','A=Pa/2',{type:'regular-polygon',labels:['P','a']},[choice('Perímetro 30 cm e apótema 4 cm. Área?',['30','34','60','120','240'],2,'A=30·4/2=60 cm².'),choice('Área 96 m² e perímetro 24 m. O apótema é',['4','6','8','12','16'],2,'a=2A/P=192/24=8 m.')]),
 geom('pavimentacao','Pavimentações e ângulos','Uma pavimentação regular exige que ângulos em torno de um vértice somem 360°.','k·α=360°',{type:'tiling',labels:['α','360°']},[choice('Quantos quadrados regulares se encontram em um vértice de uma pavimentação?',['2','3','4','5','6'],2,'Cada ângulo mede 90°; 360/90=4.'),choice('Triângulos equiláteros de 60° em torno de um vértice formam',['4','5','6','7','8'],2,'360/60=6 triângulos.')]),
 geom('simetria','Simetrias no plano','Reflexões preservam distâncias e invertem a orientação; rotações preservam forma e tamanho.','isometrias preservam comprimento',{type:'symmetry',labels:['eixo','P']},[choice('A reflexão do ponto (3,−2) em relação ao eixo x é',['(−3,−2)','(3,2)','(−3,2)','(2,3)','(3,−2)'],1,'Na reflexão em x, (x,y)→(x,−y).'),choice('A reflexão de (−4,5) em relação ao eixo y é',['(4,5)','(−4,−5)','(4,−5)','(5,−4)','(−5,4)'],0,'Na reflexão em y, (x,y)→(−x,y).')]),
 geom('rotacao','Rotação de 90°','Rotação anti-horária de 90° em torno da origem leva (x,y) a (−y,x).','(x,y)→(−y,x)',{type:'rotation',labels:['90°','P']},[choice('A rotação anti-horária de 90° de (2,1) é',['(1,−2)','(−1,2)','(−2,−1)','(2,−1)','(−1,−2)'],1,'(x,y)→(−y,x), então (2,1)→(−1,2).'),choice('A rotação anti-horária de 90° de (−3,4) é',['(4,3)','(−4,−3)','(−4,3)','(3,4)','(3,−4)'],1,'(−y,x)=(−4,−3).')]),
 geom('translacao','Translação no plano','Translação soma o mesmo vetor a todos os pontos.','(x,y)→(x+a,y+b)',{type:'translation',labels:['v','P']},[choice('Transladar (1,−2) pelo vetor (3,4) produz',['(−2,−6)','(4,2)','(3,4)','(1,2)','(−4,2)'],1,'(1+3,−2+4)=(4,2).'),choice('O vetor que leva A(2,5) a A′(−1,9) é',['(3,4)','(−3,4)','(−1,9)','(1,−4)','(−3,−4)'],1,'v=A′−A=(−3,4).')]),
 geom('homotetia','Homotetia e escala','Homotetia de razão k multiplica comprimentos por |k| e áreas por k².','A₂=k²A₁',{type:'homothety',labels:['k','P']},[choice('Uma figura de área 12 cm² sofre homotetia k=2. A nova área é',['14','24','36','48','96'],3,'A′=2²·12=48 cm².'),choice('Uma imagem é reduzida com k=1/2. Um segmento de 18 cm passa a medir',['4,5','9','12','18','36'],1,'18/2=9 cm.')]),
 geom('distancia-coordenadas','Distância entre pontos','A distância cartesiana usa Pitágoras nas diferenças de coordenadas.','d=√((x₂−x₁)²+(y₂−y₁)²)',{type:'coordinate',labels:['A','B','d']},[choice('A distância entre (1,2) e (4,6) é',['3','4','5','6','7'],2,'d=√(3²+4²)=5.'),choice('A distância entre (−2,1) e (4,9) é',['6','8','10','12','14'],2,'d=√(6²+8²)=10.')]),
 geom('ponto-medio','Ponto médio','O ponto médio é a média das coordenadas correspondentes.','M=((x₁+x₂)/2,(y₁+y₂)/2)',{type:'coordinate',labels:['A','M','B']},[choice('O ponto médio de (2,4) e (8,10) é',['(3,5)','(5,7)','(6,8)','(10,14)','(4,6)'],1,'M=(5,7).'),choice('Se M(3,−1) é ponto médio de A(1,5) e B, então B é',['(5,−7)','(4,4)','(6,−2)','(2,−6)','(−5,7)'],0,'B=2M−A=(5,−7).')]),
 geom('reta-coordenadas','Inclinação de reta','A inclinação é a razão entre variações de y e x.','m=Δy/Δx',{type:'line',labels:['m','Δx','Δy']},[choice('A reta por (1,2) e (5,10) tem coeficiente angular',['1/2','1','2','4','8'],2,'m=(10−2)/(5−1)=2.'),choice('Uma reta de inclinação −3 passa por (2,4). Quando x aumenta 2, y varia',['−6','−3','0','3','6'],0,'Δy=−3·2=−6.')]),
 geom('reta-perpendicular','Retas perpendiculares','Retas não verticais perpendiculares têm coeficientes angulares cujo produto é −1.','m₁m₂=−1',{type:'perpendicular',labels:['m','−1/m']},[choice('Uma reta de inclinação 2 é perpendicular a uma reta de inclinação',['−2','−1/2','0','1/2','2'],1,'m₂=−1/2.'),choice('A reta 3x+2y−5=0 tem inclinação; a perpendicular tem inclinação',['−3/2','−2/3','2/3','3/2','2'],3,'m=−3/2, logo perpendicular m=2/3.')]),
 geom('circunferencia-equacao','Equação da circunferência','Centro (h,k) e raio r geram (x−h)²+(y−k)²=r².','(x−h)²+(y−k)²=r²',{type:'circle-coordinate',labels:['C','r']},[choice('A equação (x−2)²+(y+3)²=25 tem centro e raio',['(−2,3), 5','(2,−3), 5','(2,3), 25','(−2,−3), 5','(3,−2), 25'],1,'Centro (2,−3) e raio 5.'),choice('O centro de x²+y²−6x+4y−3=0 é',['(−3,2)','(3,−2)','(6,−4)','(3,2)','(−3,−2)'],1,'Completando quadrados: (x−3)²+(y+2)²=16.')]),
 geom('baricentro','Baricentro do triângulo','O baricentro é a média das coordenadas dos vértices.','G=((x₁+x₂+x₃)/3,... )',{type:'triangle-coordinate',labels:['A','B','G']},[choice('O baricentro de (0,0),(6,0),(0,3) é',['(1,1)','(2,1)','(3,1)','(2,3)','(6,3)'],1,'G=(2,1).'),choice('Vértices (−3,2),(3,2),(0,8) têm baricentro',['(0,2)','(0,4)','(1,4)','(0,6)','(3,4)'],1,'G=(0,4).')]),
 geom('shoelace','Área por coordenadas','A fórmula do determinante calcula áreas de polígonos orientados.','A=|Σxᵢyᵢ₊₁−yᵢxᵢ₊₁|/2',{type:'polygon-coordinate',labels:['x','y','A']},[choice('O triângulo com vértices (0,0),(4,0),(0,3) tem área',['3','4','6','12','24'],2,'A=base·altura/2=6.'),choice('O retângulo com vértices (1,1),(5,1),(5,4),(1,4) tem área',['7','10','12','15','20'],2,'A=4·3=12.')]),
 geom('heron','Fórmula de Herão','Com lados a,b,c e semiperímetro s, A=√(s(s−a)(s−b)(s−c)).','A=√(s(s−a)(s−b)(s−c))',{type:'triangle',labels:['a','b','c']},[choice('Um triângulo de lados 3,4,5 tem área',['5','6','7','10','12'],1,'É retângulo: A=3·4/2=6.'),choice('Um triângulo de lados 5,5,6 tem área',['8','10','12','14','16'],2,'s=8; A=√(8·3·3·2)=12 cm².')]),
 geom('lei-senos','Lei dos senos','Lados e senos de ângulos opostos são proporcionais.','a/sen A=2R',{type:'triangle-angle',labels:['a','A','R']},[choice('Se a=10, A=30° e R=10, a/(sen A) vale',['5','10','15','20','30'],3,'10/0,5=20=2R.'),choice('Em um triângulo, a=8, sen A=0,5 e sen B=0,75. O lado b vale',['6','8','10','12','16'],2,'8/0,5=b/0,75, logo b=12.')]),
 geom('lei-cossenos','Lei dos cossenos','Relaciona dois lados e o ângulo compreendido; generaliza Pitágoras.','c²=a²+b²−2ab cos C',{type:'triangle-angle',labels:['a','b','C']},[choice('Dois lados 3 e 4 formam ângulo reto. O terceiro lado é',['1','3','4','5','7'],3,'cos90=0, então c²=9+16=25.'),choice('Lados 5 e 7 formam ângulo de 60°. O terceiro lado ao quadrado é',['39','49','64','74','109'],0,'c²=25+49−35=39.')]),
 geom('area-composicao','Área por composição','Decompor uma figura em partes simples permite somar ou subtrair áreas.','A_total=ΣA_partes',{type:'composite',labels:['A','B','C']},[choice('Um retângulo 10×6 tem um quadrado 2×2 retirado. A área restante é',['52','56','58','60','64'],1,'60−4=56.'),choice('Uma figura é formada por dois retângulos de áreas 24 e 15 sem sobreposição. Área total?',['9','24','30','39','45'],3,'A soma é 24+15=39.')]),
 geom('coroa-circular','Coroa circular','A área da coroa é a diferença entre os círculos externo e interno.','A=π(R²−r²)',{type:'annulus',labels:['R','r']},[choice('Com π=3, R=5 e r=3. Área da coroa?',['12','24','36','48','75'],1,'A=3(25−9)=48; opção D.',3)]),
 geom('triangulo-isosceles','Propriedades do isósceles','Em um isósceles, ângulos da base são iguais e a mediana à base também é altura.','base angles equal',{type:'isosceles',labels:['a','a','v']},[choice('Um isósceles tem lados iguais 13 e base 10. Sua altura à base é',['5','10','12','13','18'],2,'A metade da base é 5; h=√(13²−5²)=12.'),choice('Se os ângulos da base medem 68°, o ângulo do vértice mede',['44°','54°','68°','112°','136°'],0,'180−136=44°.')]),
 geom('quadrilateros','Classificação de quadriláteros','Paralelogramo tem dois pares de lados paralelos; retângulo tem ângulos retos; losango tem quatro lados iguais.','propriedades definem classes',{type:'quadrilateral',labels:['90°','∥']},[choice('Qual propriedade é comum a todo retângulo?',['Quatro lados iguais','Diagonais perpendiculares sempre','Quatro ângulos retos','Apenas um par paralelo','Nenhum lado paralelo'],2,'Todo retângulo tem quatro ângulos retos.'),choice('Um quadrado é simultaneamente',['apenas trapézio','retângulo e losango','círculo e losango','triângulo e retângulo','paralelogramo sem lados iguais'],1,'Ele tem ângulos retos e quatro lados iguais.')]),
 geom('circunferencias-posicoes','Posições relativas de circunferências','A soma e a diferença dos raios determinam relações externa, tangente ou secante.','d compare R+r and |R−r|',{type:'two-circles',labels:['R','r','d']},[choice('Dois círculos de raios 5 e 3 são tangentes externamente quando a distância dos centros é',['2','3','5','8','15'],3,'Tangência externa: d=R+r=8.'),choice('Com R=7 e r=2, a tangência interna ocorre em d=',['2','5','7','9','14'],1,'Tangência interna: d=R−r=5.')])
].forEach(addGeom);

const phys=(id,subtopic,summary,correct,wrong,application,applicationExplain)=>({id:'fis-energia-'+id,discipline:'fisica',topic:'Energia, dinâmica e trabalho',subtopic,summary,correct,wrong,context:'Use unidades do SI e despreze perdas não mencionadas.',application,applicationExplain});
[
 phys('leis-newton','Leis de Newton','A força resultante relaciona-se à aceleração pela segunda lei; ação e reação atuam em corpos diferentes.','A força resultante é F=ma.',['Velocidade é sempre igual à força.','Ação e reação se anulam no mesmo corpo.','Massa mede aceleração.','Força resultante independe da massa.'],'Um corpo de 2 kg sob resultante de 6 N acelera 3 m/s².','Aplicar F=ma exige identificar a resultante e a massa.'),
 phys('inercia','Inércia','Sem resultante, um corpo mantém repouso ou movimento retilíneo uniforme.','A ausência de força resultante não exige repouso.',['Todo corpo sem força para imediatamente.','Inércia é uma força extra.','Movimento uniforme exige força resultante constante.','Massa não influencia inércia.'],'Um ônibus freia e passageiros tendem a seguir para frente.','O corpo conserva seu estado, enquanto o veículo muda sua velocidade.'),
 phys('acao-reacao','Ação e reação','Forças de ação e reação têm mesmo módulo e sentidos opostos, em corpos distintos.','O par gravitacional Terra-corpo atua em corpos diferentes.',['As forças somam zero sempre no mesmo corpo.','A reação ocorre depois de um atraso.','Só corpos em contato têm ação e reação.','Ação é maior que reação.'],'Ao caminhar, o pé empurra o chão e o chão empurra o pé.','O par explica a aceleração do caminhante sem ser uma força duplicada no mesmo diagrama.'),
 phys('atrito','Atrito','O atrito se opõe ao movimento relativo ou à tendência de movimento e depende da normal no modelo seco simples.','O atrito cinético pode ser modelado por f=μN.',['Atrito sempre aponta para cima.','Atrito não depende da normal.','Atrito cria energia líquida.','Atrito é igual ao peso em qualquer situação.'],'Duplicar a normal mantendo μ dobra o atrito cinético.','No modelo, f=μN; a direção depende do deslizamento relativo.'),
 phys('plano-inclinado','Plano inclinado','Componentes do peso em um plano inclinado permitem analisar movimento e equilíbrio.','A componente paralela do peso é mg senθ.',['A componente paralela é mg cosθ sempre.','Peso desaparece no plano.','Normal é sempre igual ao peso total.','Ângulo não altera componentes.'],'Em uma rampa mais inclinada, a componente do peso ao longo da rampa aumenta.','A decomposição usa o ângulo geométrico da inclinação.'),
 phys('circular','Movimento circular','A aceleração centrípeta aponta para o centro e tem módulo v²/R.','Movimento circular uniforme tem aceleração mesmo com velocidade escalar constante.',['A aceleração é tangente sempre.','Não há aceleração se o módulo da velocidade é constante.','A centrípeta aponta para fora.','Raio maior aumenta v²/R em v fixo.'],'Duplicar a velocidade quadruplica a aceleração centrípeta.','A direção da velocidade muda continuamente.'),
 phys('gravidade','Gravitação','A força gravitacional diminui com o quadrado da distância entre centros.','F é proporcional a m₁m₂/r².',['A gravidade cresce com r².','Massa não influencia gravidade.','A força só existe na atmosfera.','A distância não importa.'],'Duplicar a distância reduz a força gravitacional a um quarto.','A dependência quadrática é central à lei de Newton.'),
 phys('trabalho-forca','Trabalho de força constante','O trabalho é W=Fd cosθ para força constante e deslocamento retilíneo.','Uma força perpendicular ao deslocamento realiza trabalho nulo.',['Força perpendicular sempre realiza trabalho máximo.','Trabalho é força dividida por distância.','Trabalho não pode ser negativo.','Ângulo não importa.'],'Uma força de 20 N desloca um bloco 3 m na mesma direção e realiza 60 J.','O sinal depende do ângulo entre força e deslocamento.'),
 phys('trabalho-peso','Trabalho do peso','O trabalho do peso depende da variação de altura e é positivo na descida.','Na descida de altura h, o peso realiza mgh de trabalho.',['Peso realiza trabalho nulo sempre.','Subir aumenta trabalho do peso.','Peso depende do caminho em campo uniforme.','Trabalho do peso é energia cinética sempre.'],'Um corpo de 2 kg desce 5 m com g=10 e recebe 100 J do peso.','Forças conservativas permitem relacionar trabalho e energia potencial.'),
 phys('energia-cinetica','Energia cinética','A energia cinética é K=mv²/2 e depende do quadrado da velocidade.','Dobrar a velocidade quadruplica K.',['Dobrar velocidade dobra K.','K depende apenas da altura.','K pode ser negativa.','Massa não influencia K.'],'Um corpo de 2 kg a 3 m/s tem K=9 J.','O quadrado da velocidade explica a sensibilidade a mudanças de rapidez.'),
 phys('energia-potencial','Energia potencial gravitacional','Perto da superfície, U=mgh tomando referência de altura.','Escolher outra referência soma uma constante sem alterar variações de energia.',['U absoluta é única e obrigatória.','Altura não importa.','Massa não importa.','Potencial só existe no vácuo.'],'Elevar 3 kg em 2 m com g=10 aumenta U em 60 J.','O que produz trabalho em problemas é ΔU.'),
 phys('conservacao','Conservação da energia','A energia total se conserva; forças dissipativas transformam energia mecânica em térmica, por exemplo.','Em queda sem resistência, K+U permanece constante.',['Energia desaparece com atrito.','Atrito aumenta energia mecânica.','Conservação exige velocidade constante.','Energia potencial não pode virar cinética.'],'Uma queda transforma parte de U em K enquanto a soma se mantém.','A forma da energia muda, mas a contabilidade total permanece.'),
 phys('mola','Energia elástica','Uma mola ideal armazena Ue=kx²/2.','Comprimir a deformação ao dobro quadruplica a energia elástica.',['Energia é linear em x.','Mola ideal não armazena energia.','k não importa.','A energia é negativa sempre.'],'Uma mola k=200 N/m comprimida 0,1 m armazena 1 J.','A lei de Hooke e o trabalho da força elástica geram a expressão quadrática.'),
 phys('potencia','Potência mecânica','Potência é a taxa de transformação de energia ou trabalho, P=W/Δt.','Fazer o mesmo trabalho em metade do tempo dobra a potência média.',['Potência é trabalho vezes tempo.','Potência independe de tempo.','Potência é sempre energia total.','Unidade de potência é joule.'],'Um motor realiza 600 J em 3 s e tem potência média 200 W.','Watt equivale a joule por segundo.'),
 phys('rendimento','Rendimento','Rendimento é a razão entre energia ou potência útil e fornecida.','η=Eútil/Efornecida, geralmente menor que 1 em sistemas reais.',['Rendimento é energia fornecida/útil.','Rendimento real supera 100%.','Perdas aumentam energia útil.','Rendimento não tem unidade.'],'Uma máquina recebe 1000 J e entrega 700 J úteis: η=70%.','A diferença representa perdas ou transformações não aproveitadas.'),
 phys('impulso','Impulso','Impulso é I=FΔt e equivale à variação da quantidade de movimento.','Aumentar o tempo de contato para a mesma variação de momento reduz a força média.',['Impulso é massa dividida por tempo.','Força média cresce com tempo sempre.','Impulso não altera movimento.','Momento não depende de velocidade.'],'Airbags aumentam o tempo da colisão e reduzem a força média.','I=Δp conecta interação temporal e mudança de movimento.'),
 phys('momento','Quantidade de movimento','Momento linear é p=mv e é vetorial.','Em sistema isolado, o momento total se conserva.',['Momento é escalar.','Massa não importa.','Sistema isolado perde momento.','Velocidade não tem direção.'],'Em uma colisão curta sem impulso externo, a soma dos momentos antes e depois é igual.','A conservação é vetorial e deve considerar sinais.'),
 phys('colisao-inelastica','Colisão inelástica','Em colisão perfeitamente inelástica, os corpos ficam unidos; momento conserva-se, energia cinética não.','A energia cinética pode diminuir enquanto o momento total se conserva.',['Energia cinética sempre conserva.','Momento não conserva.','Corpos nunca se unem.','A velocidade final é a soma das iniciais.'],'Dois carrinhos que grudam compartilham velocidade final obtida pelo momento.','A diferença de energia vira deformação, som e calor.'),
 phys('colisao-elastica','Colisão elástica','Em colisão elástica ideal, momento e energia cinética conservam-se.','A soma das energias cinéticas antes e depois é igual.',['Somente a energia potencial conserva.','Momento desaparece.','A colisão exige corpos idênticos.','Energia cinética sempre aumenta.'],'Bolas de bilhar aproximam um modelo de colisão elástica.','O modelo idealiza deformações e perdas pequenas.'),
 phys('centro-massa','Centro de massa','O centro de massa de um sistema pondera posições pelas massas.','O centro de massa pode estar fora do material de um corpo, como em um anel.',['Sempre está dentro da matéria.','Ignora massa.','Só existe em corpos pontuais.','Não se move com forças externas.'],'O centro de massa de uma placa anular fica no centro geométrico vazio.','A posição é uma média ponderada, não uma região obrigatoriamente ocupada.'),
 phys('torque','Torque e equilíbrio','Torque mede tendência de rotação e depende da força e do braço perpendicular.','τ=F·d⊥.',['Torque é força sem distância.','Braço paralelo maximiza torque.','Equilíbrio translacional garante rotação nula.','Todo torque é igual ao peso.'],'Uma maçaneta distante da dobradiça exige menor força para o mesmo torque.','Equilíbrio completo exige soma de forças e torques nulas.'),
 phys('alavanca','Alavancas','Alavancas equilibram momentos em torno do apoio.','F₁d₁=F₂d₂ no equilíbrio ideal.',['Braços não importam.','Forças sempre iguais.','O apoio não exerce força.','Momento não depende de distância.'],'Dobrar o braço de potência permite metade da força para a mesma resistência.','A vantagem mecânica troca força por distância.'),
 phys('pressao','Pressão e força','Pressão é p=F/A e aumenta quando a mesma força atua em área menor.','A pressão é inversamente proporcional à área de contato.',['Pressão é força vezes área.','Área maior sempre aumenta pressão.','Pressão só existe em gases.','Força não importa.'],'Uma lâmina afiada concentra força em área pequena.','A distribuição da força explica o efeito mecânico.'),
 phys('empuxo','Empuxo','O empuxo é igual ao peso do fluido deslocado, pelo princípio de Arquimedes.','Um corpo totalmente imerso desloca volume igual ao seu próprio volume.',['Empuxo depende apenas da massa do corpo.','Fluido não exerce força vertical.','Empuxo aponta para baixo.','Volume deslocado é sempre zero.'],'A força de empuxo em água é ρágua g Vdeslocado.','Densidade do fluido e volume deslocado determinam o módulo.'),
 phys('vazao','Vazão e continuidade','Vazão volumétrica é Q=Av; em fluido incompressível, Av é constante ao longo do tubo.','Ao estreitar o tubo, a velocidade aumenta se a vazão se conserva.',['Velocidade diminui sempre no estreitamento.','Área não importa.','Fluido incompressível não se move.','Vazão é massa vezes área.'],'Se a área cai à metade, a velocidade dobra para a mesma vazão.','A continuidade liga área da seção e velocidade média.'),
 phys('energia-termica','Energia térmica e trabalho','Trabalho e calor são modos de transferência de energia; a energia interna pode mudar sem ser “substância”.','Calor flui espontaneamente do corpo de maior temperatura para o de menor.',['Calor é armazenado como material.','Temperatura é energia total.','Trabalho não transfere energia.','Frio flui como líquido.'],'Ao comprimir um gás rapidamente, trabalho pode aumentar sua energia interna.','É preciso distinguir temperatura, calor e energia interna.'),
 phys('mecanica-energia','Teorema trabalho-energia','O trabalho da força resultante é igual à variação da energia cinética.','Wres=ΔK.',['Wres é sempre igual a K final.','Trabalho resultante não muda velocidade.','A relação vale só em repouso.','Energia cinética não tem unidade.'],'Se o trabalho resultante é 40 J, a energia cinética aumenta 40 J.','A soma dos trabalhos das forças explica a mudança de rapidez.'),
 phys('gravidade-potencial','Potencial gravitacional','Em campo uniforme próximo à Terra, ΔU=mgΔh; em órbita, a referência deve considerar a lei gravitacional.','Subir aumenta U gravitacional no modelo próximo à superfície.',['Subir sempre diminui U.','U não depende de g.','Altura não é uma coordenada.','Toda órbita tem U zero.'],'Duas massas iguais elevadas à mesma altura ganham a mesma energia potencial.','A escolha da referência não altera diferenças de energia.'),
 phys('forca-elastica','Força elástica','A força restauradora de mola ideal é F=−kx.','O sinal negativo indica oposição à deformação.',['A força aponta sempre para fora.','F independe de x.','k mede massa.','Mola ideal não retorna ao equilíbrio.'],'Duplicar a deformação dobra o módulo da força elástica.','O sentido restaurador é essencial ao movimento oscilatório.')
].forEach(s=>addGeneric(s,ids.fis,'fisica-foco'));

const geo=(subtopic,summary,correct,wrong,application,applicationExplain)=>({id:'geo-geomorf-'+subtopic.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'),discipline:'geografia',topic:'Geomorfologia',subtopic,summary,correct,wrong,application,applicationExplain});
[
 geo('Tectônica de placas','A dinâmica interna da Terra movimenta placas e participa da formação de montanhas, vulcões e terremotos.','Convergência de placas pode formar cadeias montanhosas e zonas de subducção.',['Placas são imóveis.','Relevo depende apenas de chuva.','Subducção ocorre em limites divergentes.','Terremotos só surgem em rios.'],'A colisão de placas continentais pode espessar a crosta e elevar o relevo.','Processos endógenos criam estruturas sobre as quais a erosão atua.'),
 geo('Ciclo das rochas','Rochas ígneas, sedimentares e metamórficas transformam-se por fusão, solidificação, compactação, cimentação, pressão e temperatura.','Uma rocha sedimentar pode sofrer metamorfismo sem derreter completamente.',['Toda rocha nasce sedimentar.','Metamorfismo é sempre fusão.','Rochas não se transformam.','Magma é rocha sedimentar.'],'Enterramento e aumento de pressão podem recristalizar minerais.','O ciclo é aberto a diferentes trajetórias conforme condições.'),
 geo('Intemperismo físico','Intemperismo físico fragmenta rochas sem alterar essencialmente sua composição química.','Variações térmicas e congelamento da água em fraturas podem promover desagregação.',['Dissolução é sempre física.','Intemperismo físico funde rochas.','Não há fraturas no processo.','Somente raízes causam fragmentação.'],'Em clima com grande amplitude térmica, expansão e contração repetidas podem abrir fraturas.','Fragmentos aumentam a área exposta a outros processos.'),
 geo('Intemperismo químico','Intemperismo químico altera minerais por água, oxigênio, ácidos e reações de hidrólise.','Clima quente e úmido favorece alterações químicas intensas em muitos minerais.',['Clima úmido impede reações.','Oxidação não altera minerais.','Intemperismo químico só ocorre no gelo.','Dissolução não remove íons.'],'A água acidificada pode dissolver minerais carbonáticos.','Disponibilidade de água e temperatura controlam taxas de reação.'),
 geo('Erosão fluvial','Rios erodem, transportam e depositam sedimentos, formando vales, meandros, planícies e deltas.','A velocidade da água e a carga sedimentar influenciam a capacidade de erosão.',['Rios apenas depositam.','Meandros são formados por vento.','Sedimentos não se movem.','Declividade não interfere.'],'Aumentar a vazão durante uma cheia pode ampliar erosão de margens.','Energia do fluxo muda com vazão, declividade e rugosidade.'),
 geo('Bacia hidrográfica','Bacia é área drenada por um curso principal e seus afluentes, delimitada por divisores de água.','O divisor topográfico separa fluxos que seguem para bacias distintas.',['Bacia é apenas o leito.','Afluentes não pertencem à bacia.','Divisor fica sempre no mar.','Drenagem ignora relevo.'],'Impermeabilização a montante pode elevar picos de vazão a jusante.','Processos geomorfológicos e uso do solo se conectam na escala da bacia.'),
 geo('Meandros e planícies','Meandros migram por erosão na margem externa e deposição na interna; planícies aluviais acumulam sedimentos.','A margem côncava tende a ter maior velocidade e erosão.',['Margem interna sempre erode mais.','Meandros não migram.','Planície é área sem sedimentos.','Velocidade é igual em toda curva.'],'Cortar um meandro pode formar lagoa marginal.','A dinâmica lateral do rio produz formas e depósitos.'),
 geo('Leques aluviais','Leques aluviais formam-se quando um fluxo perde energia ao sair de área íngreme para superfície mais plana.','A redução da declividade favorece deposição radial de sedimentos.',['A deposição ocorre no topo da montanha.','Leques são glaciais sempre.','Fluxo aumenta energia ao achatar.','Não há sedimentos.'],'A saída de um cânion para uma planície pode originar leque aluvial.','Mudança de energia controla seleção e distribuição dos materiais.'),
 geo('Deltas','Deltas são depósitos na foz fluvial quando a descarga de sedimentos supera a remoção por ondas e correntes.','A formação de delta depende do balanço entre aporte sedimentar e energia costeira.',['Todo rio forma delta.','Ondas não afetam foz.','Delta ocorre apenas em desertos.','Sedimentos não se depositam na foz.'],'Redução de sedimentos por barragens pode diminuir a construção de um delta.','A forma resulta da interação rio-mar.'),
 geo('Carste','Relevo cárstico desenvolve-se pela dissolução de rochas solúveis, formando cavernas, dolinas e rios subterrâneos.','Calcário e água acidificada são condições comuns em paisagens cársticas.',['Carste depende de granito insolúvel apenas.','Dolina é duna.','Cavernas são vulcânicas sempre.','Água não circula no subsolo.'],'Contaminação superficial pode alcançar rapidamente aquíferos cársticos.','A permeabilidade por fraturas e condutos aumenta a vulnerabilidade.'),
 geo('Glaciação','Gelo em movimento erode e transporta sedimentos, produzindo vales em U e morainas.','Vales glaciais tendem a ter seção transversal em U.',['Geleiras formam vales em V exclusivamente.','Gelo não transporta sedimentos.','Moraina é depósito marinho.','Glaciação não altera relevo.'],'O recuo de uma geleira pode deixar depósitos frontais.','Erosão e deposição glacial registram posições antigas do gelo.'),
 geo('Geomorfologia eólica','Vento remove, transporta e deposita partículas, formando dunas e feições de deflação.','A ação eólica é mais eficiente onde há sedimentos soltos e pouca cobertura vegetal.',['Vento só atua em florestas densas.','Dunas são formadas por rios.','Deflação adiciona sedimento ao solo.','Vegetação não interfere.'],'Retirar vegetação de uma área seca pode intensificar mobilização de areia.','Cobertura vegetal estabiliza sedimentos.'),
 geo('Geomorfologia costeira','Ondas, marés e correntes remodelam praias, falésias, restingas e cordões litorâneos.','A abrasão das ondas pode recuar falésias e produzir plataformas de abrasão.',['Falésias são exclusivamente fluviais.','Ondas não erodem rocha.','Restingas são montanhas.','Marés não movimentam sedimentos.'],'Obras costeiras podem alterar transporte longitudinal de areia.','A costa é um sistema de erosão, transporte e deposição.'),
 geo('Movimentos de massa','Deslizamentos e quedas de blocos deslocam material pela gravidade e dependem de declividade, água, solo e uso da terra.','A saturação do solo pode aumentar peso e reduzir resistência ao cisalhamento.',['Chuva sempre estabiliza encostas.','Declividade não importa.','Deslizamento é causado somente por terremoto.','Vegetação aumenta sempre risco.'],'Cortes sem drenagem em encostas podem favorecer deslizamentos.','Prevenção combina drenagem, cobertura e planejamento.'),
 geo('Solos e perfil','Horizontes do solo resultam de interação entre material de origem, clima, organismos, relevo e tempo.','A matéria orgânica tende a concentrar-se no horizonte superficial.',['Solo é rocha intacta.','Clima não altera solo.','Horizontes são camadas de lava.','Tempo não importa.'],'Remover a camada superficial reduz fertilidade e aumenta erosão.','A formação do solo é lenta e espacialmente variável.'),
 geo('Laterização','Em climas tropicais úmidos, lixiviação intensa pode concentrar óxidos de ferro e alumínio, formando solos lateríticos.','A laterização está associada a intemperismo químico e lixiviação intensos.',['Laterização é congelamento.','Óxidos são removidos todos.','Clima úmido impede lixiviação.','Laterita só ocorre no Ártico.'],'Desmatamento e manejo inadequado podem expor horizonte endurecido e pobre.','O processo liga clima, solo e uso da terra.'),
 geo('Escudos cristalinos','Escudos são estruturas antigas, compostas sobretudo por rochas cristalinas, frequentemente associadas a minerais metálicos.','Escudos tendem a apresentar rochas antigas e grande estabilidade relativa.',['Escudos são depósitos sedimentares recentes.','Não contêm minerais.','Formam-se apenas em deltas.','São sempre planícies aluviais.'],'Áreas de escudo podem concentrar mineração, com impactos geomorfológicos.','A estrutura geológica condiciona relevo e recursos.'),
 geo('Bacias sedimentares','Bacias sedimentares acumulam camadas de sedimentos e podem registrar fósseis e recursos energéticos.','A subsidência e o aporte sedimentar favorecem preenchimento de bacias.',['Bacias não acumulam sedimentos.','São feitas apenas de magma.','Não registram passado ambiental.','Sempre coincidem com escudos.'],'Camadas sedimentares podem preservar diferentes ambientes antigos.','Estratigrafia relaciona tempo, deposição e paisagem.'),
 geo('Relevo brasileiro','O relevo brasileiro é majoritariamente antigo e modelado por intemperismo e erosão, embora existam diferentes estruturas e formas.','Planaltos, planícies e depressões são formas classificadas pela dinâmica predominante, não apenas pela altitude.',['Planalto é sempre mais alto que planície.','Planície não recebe sedimentos.','Depressão é necessariamente abaixo do nível do mar.','Altitude sozinha define todas as formas.'],'Uma planície fluvial pode ser baixa e acumular sedimentos recentes.','Classificações geomorfológicas consideram gênese e processos.'),
 geo('Superfícies de aplainamento','Aplainamento reduz irregularidades por ação prolongada de intemperismo e erosão, com soerguimentos e mudanças climáticas influenciando a preservação.','Superfícies aplainadas podem ser antigas e posteriormente dissecadas.',['Aplainamento eleva todo relevo.','Erosão nunca aplaina.','Toda superfície é recente.','Soerguimento é deposição.'],'Um rio encaixado pode dissecar uma superfície previamente mais plana.','O relevo atual combina fases de construção e destruição.'),
 geo('Drenagem e relevo','Padrões de drenagem refletem estrutura geológica, declividade e resistência das rochas.','Drenagem treliça pode associar-se a camadas resistentes e dobradas.',['Rios não respondem à estrutura.','Todo padrão é dendrítico.','Declividade não afeta fluxo.','Drenagem é independente de rochas.'],'Fraturas e falhas podem orientar trechos retilíneos de rios.','A rede hidrográfica registra controles estruturais.'),
 geo('Geomorfologia urbana','Urbanização modifica escoamento, estabilidade de encostas e transporte de sedimentos.','Impermeabilização aumenta escoamento superficial e pode reduzir infiltração.',['Asfalto aumenta infiltração.','Cidades não alteram rios.','Canalização sempre recupera ecossistemas.','Urbanização elimina erosão.'],'Bacias urbanizadas podem ter enchentes rápidas após chuva intensa.','Planejamento deve considerar relevo, drenagem e ocupação.'),
 geo('Mineração e relevo','Mineração remove cobertura, altera encostas, pilhas e drenagem, produzindo impactos geomorfológicos.','Cavas e pilhas de estéril modificam topografia e podem concentrar erosão.',['Mineração não remove material.','Pilhas estabilizam sempre.','Drenagem não muda.','Impacto é apenas visual.'],'Recuperação de área minerada exige reconfiguração, drenagem e revegetação.','A mitigação precisa tratar processos, não apenas aparência.'),
 geo('Desmatamento e erosão','A remoção vegetal reduz interceptação e raízes, deixando solo mais exposto à chuva e ao escoamento.','A cobertura vegetal geralmente diminui erosão laminar e formação de ravinas.',['Desmatamento reduz escoamento.','Raízes não estabilizam solo.','Vegetação sempre causa ravina.','Chuva não transporta sedimentos.'],'Manter mata ciliar reduz erosão das margens e assoreamento.','Conservação da cobertura atua na fonte do processo.'),
 geo('Clima e formas de relevo','Climas diferentes combinam intemperismo e erosão distintos, produzindo paisagens específicas.','Ambientes áridos favorecem amplitude térmica e processos eólicos, enquanto úmidos intensificam alterações químicas.',['Clima não interfere no relevo.','Todos os climas produzem as mesmas formas.','Aridez impede erosão.','Umidade sempre congela água.'],'A interpretação de uma paisagem deve cruzar litologia e clima.','O clima controla água, temperatura e cobertura, mas não age sozinho.'),
 geo('Andes e orogênese','A cordilheira dos Andes resulta da subducção da placa de Nazca sob a Sul-Americana.','A margem oeste da América do Sul é uma zona ativa de terremotos e vulcanismo.',['Andes surgiram de divergência oceânica.','Não há vulcões andinos.','A placa de Nazca é continental estável.','O relevo não tem relação com placas.'],'A subducção explica fossas oceânicas, vulcões e soerguimento andino.','Processos internos e externos se combinam na cordilheira.'),
 geo('Rios voçorocas e ravinas','Ravinas e voçorocas são formas erosivas associadas à concentração do escoamento em solos expostos.','Voçorocas são maiores e mais profundas que ravinas e podem atingir o lençol freático.',['Voçoroca é depósito eólico.','Ravina não depende de escoamento.','Solo coberto sempre forma voçoroca.','Ambas são formas vulcânicas.'],'Estradas mal drenadas podem concentrar água e iniciar ravinamento.','Drenagem e manejo de encostas são medidas preventivas.')
].forEach(s=>addGeneric(s,ids.geo,'geomorfologia'));

fs.writeFileSync(file,JSON.stringify(bank,null,2)+'\n');
console.log(`Banco expandido: ${bank.questions.length} questões, ${bank.concepts.length} conceitos.`);
