import {SUBJECTS,DIFFICULTIES,CONFIDENCE} from './config.js';
import {escapeHTML,clamp,sum,formatDate,relativeDue} from './utils.js';
import {masteryValue} from './mastery.js';
export const subjectById = id => SUBJECTS.find(s=>s.id===id)||SUBJECTS[0];
export const conceptById = (bank,id) => bank.concepts.find(c=>c.id===id);
export const questionById = (bank,id) => bank.questions.find(q=>q.id===id);
export const safeLink = url => {try{const u=new URL(url);return u.protocol==='https:'?escapeHTML(u.href):'#';}catch{return '#';}};
export const titleBlock = (eyebrow,title,subtitle='',extra='') => `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}<span>.</span></h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${extra}</div>`;
export const bar = (value,label='Domínio') => `<div class="progress" role="progressbar" aria-label="${escapeHTML(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${clamp(value,0,100)}"><span style="width:${clamp(value,0,100)}%"></span></div>`;
export const empty = (title,text,action='',label='') => `<div class="empty-state"><span class="empty-symbol" aria-hidden="true">◇</span><h2>${title}</h2><p>${text}</p>${action?`<button class="primary" data-action="${action}">${label} →</button>`:''}</div>`;
export const button = (label,action,id='',cls='secondary') => `<button class="${cls}" data-action="${action}" data-id="${escapeHTML(id)}">${label}</button>`;
export function favorite(state,type,id){const active=state.favorites.includes(type+':'+id);const label=type==='q'?'questão':type==='c'?'flashcard':'explicação';return `<button class="icon-button favorite ${active?'is-favorite':''}" data-action="favorite" data-id="${escapeHTML(type+':'+id)}" aria-label="${active?'Remover dos favoritos':'Favoritar'} ${label}" aria-pressed="${active}">${active?'★':'☆'}</button>`;}
export function subjectMastery(state,bank,id){const concepts=bank.concepts.filter(c=>c.discipline===id);return concepts.length?Math.round(sum(concepts.map(c=>masteryValue(state.concepts[c.id],state.reviews[c.id])))/concepts.length):0;}
export function subjectTile(state,bank,s){const m=subjectMastery(state,bank,s.id),count=bank.questions.filter(q=>q.discipline===s.id).length;return `<button class="subject-card" data-action="subject" data-id="${s.id}" style="--subject-color:${s.color}"><span class="subject-symbol">${s.icon}</span><span class="subject-percent">${m}%</span><h3>${s.name}</h3><p>${count} questões · ${m?'Em desenvolvimento':'Começar a aprender'}</p>${bar(m,s.name)}</button>`;}
export function sourceTrail(concept,curriculum){return `<details class="source-details"><summary>FUVEST 2027 → ${subjectById(concept.discipline).name} → ${escapeHTML(concept.topic)} → ${escapeHTML(concept.subtopic)}</summary><div><p>Questão autoral. Vínculos ao programa oficial:</p>${concept.officialIds.map(id=>{const o=curriculum.objects.find(o=>o.id===id);return o?`<a href="${curriculum.sourceUrl}#page=${o.page}" target="_blank" rel="noopener">${escapeHTML(o.area)} · p. ${o.page}<br>${escapeHTML(o.text)} ↗</a>`:'';}).join('')}${concept.discipline==='literatura'?'<p>Literatura é uma trilha pedagógica dentro de Língua Portuguesa no programa oficial.</p>':''}</div></details>`;}
export function answerText(q,answer){if(answer===undefined||answer===null||answer==='')return 'Não respondida';if(q.type==='order')return Array.isArray(answer)?answer.map(i=>q.options[i]||'?').join(' → '):String(answer);if(q.type==='match')return Array.isArray(answer)?answer.map((i,n)=>`${q.matchLeft[n]} → ${q.options[i]||'?'}`).join('; '):String(answer);if(['choice','boolean'].includes(q.type))return q.options[answer]||String(answer);return String(answer);}
export function questionCard(state,bank,q){const c=conceptById(bank,q.conceptId),s=subjectById(c.discipline);return `<article class="question-preview"><div class="row"><span class="tag" style="color:${s.color}">${s.name} · ${escapeHTML(c.subtopic)}</span>${favorite(state,'q',q.id)}</div><h3>${escapeHTML(q.prompt)}</h3><div class="row"><span class="meta">${DIFFICULTIES[q.difficulty]} · ${q.estimatedSeconds} s</span>${button('Resolver →','question',q.id,'text-button')}</div></article>`;}
export function conceptLine(state,c){const m=masteryValue(state.concepts[c.id],state.reviews[c.id]);return `<button class="concept-row" data-action="concept" data-id="${c.id}"><span><strong>${escapeHTML(c.subtopic)}</strong><small>${escapeHTML(c.topic)}</small></span><span class="concept-progress">${bar(m)}<b>${m}%</b></span><span>→</span></button>`;}
export function errorCard(state,bank,curriculum,error){const q=questionById(bank,error.questionId);if(!q)return '';const c=conceptById(bank,q.conceptId);const count=Object.values(state.errors).filter(e=>e.conceptId===c.id).reduce((s,e)=>s+e.count,0);return `<article class="error-card ${error.resolved?'resolved':''}"><div class="row"><span class="tag">${subjectById(c.discipline).name} · ${escapeHTML(c.subtopic)}</span><span class="tag ${error.resolved?'success':error.falseConfidence?'danger':'warning'}">${error.resolved?'Superado':error.falseConfidence?'Falso domínio':'Revisar conceito'}</span></div><h3>${escapeHTML(q.prompt)}</h3><div class="answer-comparison"><div><small>Sua resposta</small><p>${escapeHTML(answerText(q,error.answer))}</p></div><div><small>Resposta correta</small><p>${escapeHTML(answerText(q,q.answer))}</p></div></div><details><summary>Entender este erro</summary><p>${escapeHTML(q.explanation)}</p>${sourceTrail(c,curriculum)}</details><div class="row wrap"><span class="meta">${formatDate(error.lastAt)} · ${count} erro${count!==1?'s':''} neste conceito · ${CONFIDENCE[error.confidence]}</span>${button('Praticar outra abordagem →','variation',c.id,'text-button')}</div></article>`;}
