import {BANK,CURRICULUM,BOOKS} from './catalog.js';
import {NAV,SUBJECTS,MODE_NAMES} from './config.js';
import {escapeHTML,normalize,formatNumber,formatTime,todayKey,uid,clamp,relativeDue} from './utils.js';
import {createState,loadState,persistState,exportState,importState,validateState,SAVE_KEY} from './save.js';
import {scheduleReview,dueConcepts,isDue} from './reviews.js';
import {masteryValue} from './mastery.js';
import {profileLevel,currentStreak,addActivity,unlockAchievements} from './gamification.js';
import {createSession,pickNextQuestion,recordAnswer,finishSession,matchesQuestion} from './training.js';
import {subjectById,conceptById,questionById,bar,button,sourceTrail,favorite} from './components.js';
import {homeScreen,trainScreen,cardsScreen} from './screens.js';
import {errorsScreen,mapScreen,booksScreen,favoritesScreen,searchScreen} from './screens-library.js';
import {statsScreen,profileScreen} from './screens-profile.js';
import {settingsScreen} from './screens-settings.js';
import {sessionScreen,canSubmitDraft,draftAnswer} from './session-view.js';
import {defaultSessionBuilder,cleanSessionBuilder,builderFilters,sessionSubjects,sessionTopicKeys,SESSION_QUANTITIES} from './session-builder.js';
import {api,authScreen,adminScreen,avatar} from './account.js';

const loaded=loadState();
let state=loaded.state,storageBlocked=!!loaded.blocked;
let session=state.activeSession,flash=null,lastTick=Date.now(),toastTimeout,afterProfile=null,afterConfirm=null,pendingImport=null,syncTimeout=null;
let account={loading:true,user:null},adminData=null;
const ui={route:'home',filters:{},cardFilters:{},sessionBuilder:defaultSessionBuilder(BANK),errorFilter:'active',mapSearch:'',mapDiscipline:'',searchTerm:'',chartCount:7,bookId:null,sidebarOpen:false,adminPeriod:30};
const appElement=document.querySelector('#app'),modalElement=document.querySelector('#modal');
function applyPreferences(){const s=state.settings||{};const systemDark=s.theme==='system'&&window.matchMedia?.('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=s.theme==='dark'||systemDark?'dark':'light';document.documentElement.style.setProperty('--font-scale',String(s.fontScale||1));document.documentElement.classList.toggle('high-contrast',!!s.highContrast);document.documentElement.classList.toggle('reduce-motion',!!s.reduceMotion);}
applyPreferences();
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),4500);}
function queueServerSync(){if(!account.user)return;clearTimeout(syncTimeout);syncTimeout=setTimeout(()=>api('/api/progress',{method:'PUT',body:JSON.stringify({state,clientSavedAt:state.savedAt||Date.now()})}).catch(()=>toast('Seu progresso está salvo neste dispositivo e será sincronizado quando a conexão voltar.')),700);}
function saveProgress(){if(storageBlocked)return false;try{persistState(state);queueServerSync();return true;}catch(error){storageBlocked=true;toast('Não foi possível salvar. Exporte seu progresso pelo Perfil antes de fechar.');return false;}}
function track(eventType,metadata={}){if(account.user)api('/api/events',{method:'POST',body:JSON.stringify({eventType,metadata})}).catch(()=>{});}
async function hydrateProgress(){if(!account.user)return;try{const remote=await api('/api/progress');if(remote.progress?.state&&remote.progress.clientSavedAt>=(state.savedAt||0)){state=validateState(remote.progress.state);session=state.activeSession;persistState(state);}else await api('/api/progress',{method:'PUT',body:JSON.stringify({state,clientSavedAt:state.savedAt||Date.now()})});}catch(error){toast('O progresso local foi mantido; a sincronização será tentada novamente.');}}
function context(){return {...ui,state,bank:BANK,curriculum:CURRICULUM,books:BOOKS,session,flash,storageBlocked,account:account.user,adminData};}
function readRoute(){const parts=location.hash.slice(1).split('/');ui.route=['home','train','cards','errors','map','books','stats','favorites','profile','search','quiz','settings','admin','login','register','forgot','reset'].includes(parts[0])?parts[0]:'home';ui.bookId=parts[1]||null;}
function go(route){if(location.hash==='#'+route){readRoute();render();window.scrollTo(0,0);}else location.hash=route;}
function render(){
 if(account.loading){appElement.innerHTML='<div class="loading-screen"><span class="spinner"></span><h2>Preparando seu espaço…</h2></div>';return;}
 if(!account.user){const mode=['register','forgot','reset'].includes(ui.route)?ui.route:'login',token=location.hash.split('/')[1]||'';appElement.innerHTML=authScreen(mode,token);document.title='Entrar · FIXOU';return;}
 if(ui.route==='admin'&&!['owner','admin'].includes(account.user.role)){ui.route='home';history.replaceState(null,'','#home');toast('Esta área é exclusiva da administração.');}
 const level=profileLevel(state.xp),name=account.user.name,navRoute=ui.route==='quiz'?'train':ui.route;
 const views={home:homeScreen,train:trainScreen,cards:cardsScreen,errors:errorsScreen,map:mapScreen,books:booksScreen,stats:statsScreen,favorites:favoritesScreen,profile:profileScreen,search:searchScreen,quiz:sessionScreen,settings:settingsScreen,admin:adminScreen};
 const nav=[...NAV,...(['owner','admin'].includes(account.user.role)?[['admin','▦','Painel do dono']]:[])],title=ui.route==='admin'?'Painel do dono':ui.route==='profile'?'Seu perfil':ui.route==='search'?'Pesquisa':ui.route==='quiz'?'Em estudo':nav.find(n=>n[0]===ui.route)?.[2]||'Minha jornada';
 appElement.innerHTML=`<button class="nav-backdrop ${ui.sidebarOpen?'visible':''}" data-action="menu" aria-label="Fechar menu"></button><aside class="sidebar ${ui.sidebarOpen?'open':''}"><a class="brand" href="#home"><img class="brand-logo" src="assets/fixou-logo.png" alt="FIXOU — estudo que fica"></a><span class="nav-label">SEU ESPAÇO DE ESTUDO</span><nav aria-label="Navegação principal">${nav.map(([id,i,t])=>`<a href="#${id}" class="nav-item ${id===navRoute?'active':''}" ${id===navRoute?'aria-current="page"':''}><span aria-hidden="true">${i}</span>${t}${id==='errors'&&Object.values(state.errors).some(e=>!e.resolved)?'<i class="nav-badge"></i>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="exam-label"><span class="status-dot"></span> VESTIBULAR 2027</div><p>Um pouco hoje.<br>Mais clareza amanhã.</p><a class="profile-link" href="#profile">${avatar(account.user)}<span>${escapeHTML(name)}<small>Plano ${account.user.plan==='free'?'Free':'Pro'} · Nível ${level.level}</small></span><span>↗</span></a></div></aside><div class="workspace"><header class="topbar"><button class="menu-toggle" data-action="menu" aria-label="Abrir menu" aria-expanded="${ui.sidebarOpen}">☰</button><span class="breadcrumb">Seu aprendizado <span>/</span> ${title}</span><button class="search-top" data-action="search" aria-label="Buscar um conceito">⌕ <span>Buscar um conceito</span><kbd>/</kbd></button><a class="streak-chip" href="#stats">♨ ${currentStreak(state.activity)} ${currentStreak(state.activity)===1?'dia':'dias'}</a></header>${storageBlocked?'<div class="storage-alert">Seu progresso precisa de atenção. <a href="#profile">Abra o Perfil para exportar ou recuperar seus dados →</a></div>':''}<main id="main" tabindex="-1">${views[ui.route](context())}</main><footer>FIXOU · Estudo que fica · preparação independente para a FUVEST 2027. <a href="#profile">Fontes e progresso</a></footer></div>`;
 document.title=`${title} · FIXOU`;
}
function openModal(html){modalElement.innerHTML=html;if(!modalElement.open)modalElement.showModal();}
function closeModal(){modalElement.close();afterConfirm=null;}
function ensureProfile(action){if(state.profile?.name){action();return;}afterProfile=action;openModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Fechar">×</button><img class="modal-logo" src="assets/fixou-logo.png" alt="FIXOU — estudo que fica"><div class="eyebrow modal-eyebrow">SUA JORNADA COMEÇA AQUI</div><h2 id="modal-title">Como podemos chamar você?</h2><p>Vamos guardar sua evolução e preparar seu primeiro treino.</p><form id="onboarding-form" class="form-stack"><label>Seu nome<input name="name" required maxlength="40" autocomplete="given-name" placeholder="Digite seu nome" autofocus></label><label>Seu objetivo <span class="meta">(opcional)</span><input name="goal" maxlength="100" placeholder="Ex.: Medicina na USP"></label><button class="primary" type="submit">Começar minha jornada →</button><p class="note">Seu progresso é salvo neste navegador. Você pode exportar um backup a qualquer momento no Perfil.</p></form>`);}
function confirmAction(title,text,action,label='Continuar'){afterConfirm=action;openModal(`<h2 id="modal-title">${title}</h2><p class="modal-copy">${text}</p><div class="modal-actions">${button('Voltar','close-modal')}${button(label,'confirm-modal','','primary')}</div>`);}
function launch(mode='adaptive',filters={},questionId=null){ensureProfile(()=>{
 const start=()=>{session=createSession(state,BANK,mode,{...filters});const matching=BANK.questions.filter(q=>matchesQuestion(q,conceptById(BANK,q.conceptId),filters,state));const requested=filters.quantity==='all'?matching.length:Number(filters.quantity);if(Number.isFinite(requested)&&requested>0)session.limit=Math.min(requested,matching.length);else session.limit=Math.min(session.limit,matching.length);if(questionId)session.limit=1;state.activeSession=session;if(mode==='daily')state.daily={date:todayKey(),sessionId:session.id,items:[],completed:false};advance(questionId);go('quiz');};
 if(state.activeSession&&!state.activeSession.finished){confirmAction('Você tem um treino em andamento','As respostas já enviadas estão salvas. Você pode encerrar essa sessão para começar outra.',()=>{finishSession(state,state.activeSession);start();},'Encerrar e começar outro');}else start();
 });}
function advance(forcedId=null){
 if(!session)return;
 if(session.finished){render();return;}
 if(session.answered.length>=session.limit||session.lives<=0||session.endsAt&&Date.now()>=session.endsAt){complete();return;}
 const q=forcedId?questionById(BANK,forcedId):pickNextQuestion(state,BANK,session);
 if(!q){complete();return;}
 session.currentId=q.id;session.items.push(q.id);session.questionAt=Date.now();session.questionSeconds=0;session.feedback=null;session.phase='question';session.draft={answer:null,text:'',confidence:null,order:q.type==='order'?q.options.map((_,i)=>i):[],match:q.type==='match'?q.matchLeft.map(()=>-1):[]};
 if(session.mode==='daily'&&state.daily?.sessionId===session.id)state.daily.items.push(q.id);
 state.activeSession=session;lastTick=Date.now();saveProgress();if(ui.route==='quiz'){render();window.scrollTo(0,0);}
}
function complete(){if(!session||session.finished)return;finishSession(state,session);if(state.daily?.sessionId===session.id)state.daily.completed=true;saveProgress();render();if(ui.route==='quiz')window.scrollTo(0,0);}
function submitAnswer(){if(!session||session.finished||session.feedback)return;const q=questionById(BANK,session.currentId);if(!canSubmitDraft(q,session.draft)){toast('Escolha uma resposta e indique sua confiança.');return;}if(session.endsAt&&Date.now()>=session.endsAt){complete();return;}
 const attempt=recordAnswer(state,BANK,session,q,draftAnswer(q,session.draft),session.draft.confidence,session.questionSeconds||0);
 if(!attempt)return;saveProgress();render();document.querySelector('.feedback')?.scrollIntoView({behavior:'smooth',block:'nearest'});
}
function updateDraft(){saveProgress();const q=questionById(BANK,session.currentId),submit=document.querySelector('[data-action="submit-answer"]');if(submit)submit.disabled=!canSubmitDraft(q,session.draft);}
function startCards(kind,id){ensureProfile(()=>{const flashConcepts=BANK.concepts.filter(c=>c.flashcard&&!c.flashcard.needsReview);let concepts=kind==='one'?flashConcepts.filter(c=>c.id===id):kind==='due'?dueConcepts(state,flashConcepts):flashConcepts.filter(c=>{const status=ui.cardFilters.status;return (!ui.cardFilters.discipline||c.discipline===ui.cardFilters.discipline)&&(!ui.cardFilters.topic||c.topic===ui.cardFilters.topic)&&(!status||status==='new'&&!state.reviews[c.id]||status==='due'&&isDue(state,c.id)||status==='favorites'&&state.favorites.includes('c:'+c.id));});
 if(!concepts.length){toast('Nenhum cartão nesta seleção.');return;}flash={ids:concepts.map(c=>c.id),currentId:concepts[0].id,index:0,revealed:false,seconds:0};go('cards');});}
function rateCard(rating){if(!flash?.revealed)return;const id=flash.currentId,previous=state.reviews[id],now=Date.now(),due=!previous||isDue(state,id,now);
 if(due||rating==='forgot')state.reviews[id]=scheduleReview(previous,rating,now);
 let xp=0;if(due&&rating!=='forgot'&&(!previous?.flashRewardAt||todayKey(previous.flashRewardAt)!==todayKey(now))){xp=3;state.xp+=xp;state.reviews[id].flashRewardAt=now;}
 else if(previous?.flashRewardAt&&state.reviews[id])state.reviews[id].flashRewardAt=previous.flashRewardAt;
 if(rating==='forgot'&&state.concepts[id]){state.concepts[id].score=Math.max(0,masteryValue(state.concepts[id],previous,now)-8);state.concepts[id].lastAt=now;}
 addActivity(state,'reviews',flash.seconds,now,false,xp);unlockAchievements(state);saveProgress();toast(`Revisão salva · ${relativeDue(state.reviews[id].dueAt)}${xp?' · +3 XP':''}`);
 flash.index++;if(flash.index>=flash.ids.length){flash=null;render();return;}flash.currentId=flash.ids[flash.index];flash.revealed=false;flash.seconds=0;render();}
function downloadText(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showConcept(id){const c=conceptById(BANK,id);if(!c)return;const score=masteryValue(state.concepts[id],state.reviews[id]);openModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Fechar">×</button><div class="eyebrow">${subjectById(c.discipline).name}</div><h2 id="modal-title">${escapeHTML(c.subtopic)}</h2><p class="modal-copy">${escapeHTML(c.summary)}</p><div class="row"><span>Domínio estimado</span><strong>${score}%</strong></div>${bar(score)}<div class="modal-actions">${button('Praticar conceito →','variation',id,'primary')}${button('Revisar cartão','card',id)}${favorite(state,'c',id)}</div>${sourceTrail(c,CURRICULUM)}`);}
function handleAction(action,id,element){
 if(action==='logout'){api('/api/auth/logout',{method:'POST',body:'{}'}).finally(()=>{account.user=null;adminData=null;go('login');render();});return;}
 if(action==='remove-avatar'){api('/api/avatar',{method:'DELETE',body:'{}'}).then(()=>{account.user={...account.user,hasAvatar:false,avatarVersion:Date.now()};render();toast('Foto removida.');}).catch(e=>toast(e.message));return;}
 if(action==='admin-period'){ui.adminPeriod=Number(id);adminData=null;render();api('/api/admin/overview?days='+ui.adminPeriod).then(r=>{adminData=r.data;render();}).catch(e=>toast(e.message));return;}
 if(action==='menu'){ui.sidebarOpen=!ui.sidebarOpen;render();return;}
 if(action==='close-modal'){closeModal();afterProfile=null;return;}
 if(action==='confirm-modal'){const fn=afterConfirm;closeModal();fn?.();return;}
 if(action==='start'){launch(id,id==='practice'?ui.filters:{});return;}
 if(action==='start-session'){const builder=cleanSessionBuilder(BANK,ui.sessionBuilder);ui.sessionBuilder=builder;if(!builder.subjects.length){toast('Escolha pelo menos uma disciplina para começar.');render();return;}if(!builder.topics.length){toast('Escolha pelo menos um assunto para começar.');render();return;}if(!builder.difficulties.length){toast('Escolha pelo menos uma dificuldade para começar.');render();return;}const filters=builderFilters(builder),available=BANK.questions.filter(q=>matchesQuestion(q,conceptById(BANK,q.conceptId),filters,state));if(!available.length){toast('Nenhuma questão combina com essa seleção.');render();return;}const requested=builder.quantity==='all'?available.length:Number(builder.quantity);if(requested>available.length)toast(`Há ${available.length} questões disponíveis; a sessão usará todas elas.`);launch('practice',filters);return;}
 if(action==='session-select-all-subjects'){const subjects=sessionSubjects(BANK).map(s=>s.id);ui.sessionBuilder={...ui.sessionBuilder,subjects,topics:sessionTopicKeys(BANK,subjects)};render();return;}
 if(action==='session-clear-subjects'){ui.sessionBuilder={...ui.sessionBuilder,subjects:[],topics:[]};render();return;}
 if(action==='session-select-all-topics'){const subjects=ui.sessionBuilder.subjects||[];ui.sessionBuilder={...ui.sessionBuilder,topics:sessionTopicKeys(BANK,subjects)};render();return;}
 if(action==='session-clear-topics'){ui.sessionBuilder={...ui.sessionBuilder,topics:[]};render();return;}
 if(action==='resume'){session=state.activeSession;if(session){if(session.endsAt&&Date.now()>=session.endsAt)complete();go('quiz');}return;}
 if(action==='pause-session'){if(session?.mode==='lightning'){confirmAction('Encerrar o Relâmpago?','O cronômetro não pausa neste modo. Seu resultado será registrado agora.',()=>{complete();go('home');},'Encerrar desafio');}else{saveProgress();go('home');toast('Treino pausado e salvo.');}return;}
 if(action==='finish-session'){complete();return;}
 if(action==='select-answer'&&session&&!session.feedback){session.draft.answer=Number(id);updateDraft();render();return;}
 if(action==='confidence'&&session&&!session.feedback){session.draft.confidence=id;updateDraft();render();return;}
 if(action==='submit-answer'){submitAnswer();return;}
 if(action==='next-question'){advance();return;}
 if(action==='order-up'||action==='order-down'){if(session?.feedback)return;const a=session.draft.order,i=Number(id),j=i+(action==='order-up'?-1:1);if(j>=0&&j<a.length){[a[i],a[j]]=[a[j],a[i]];updateDraft();render();}return;}
 if(action==='favorite'){const i=state.favorites.indexOf(id);if(i<0)state.favorites.push(id);else state.favorites.splice(i,1);saveProgress();const kind=id.split(':')[0],noun=kind==='q'?'questão':kind==='c'?'flashcard':'explicação';element.classList.toggle('is-favorite',i<0);element.textContent=i<0?'★':'☆';element.setAttribute('aria-pressed',i<0?'true':'false');element.setAttribute('aria-label',(i<0?'Remover dos favoritos ':'Favoritar ')+noun);if(ui.route==='favorites')render();return;}
 if(action==='question'){const q=questionById(BANK,id);if(q)launch('practice',{subtopic:q.conceptId},id);return;}
 if(action==='variation'){closeModal();launch('practice',{subtopic:id});return;}
 if(action==='subject'){ui.filters={discipline:id};go('train');return;}
 if(action==='track'){const [kind,value]=String(id||'').split('|');const concept=kind==='concept'?conceptById(BANK,value):null;ui.filters=kind==='discipline'?{discipline:value}:concept?{discipline:concept.discipline,subtopic:value}:{topic:value};go('train');return;}
 if(action==='concept'){showConcept(id);return;}
 if(action==='clear-filters'){ui.filters={};render();return;}
 if(action==='search'){go('search');setTimeout(()=>document.querySelector('#global-search')?.focus(),0);return;}
 if(action==='profile-settings'){go('profile');return;}
 if(action==='report'){const q=questionById(BANK,id),c=q&&conceptById(BANK,q.conceptId);if(!q||!c)return;modalElement.dataset.reportQuestion=id;openModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Fechar">×</button><span class="eyebrow modal-eyebrow">REPORTAR PROBLEMA</span><h2 id="modal-title">Algo parece errado?</h2><p class="modal-copy">${escapeHTML(c.subtopic)} · ${escapeHTML(q.source||'Questão original')}</p><form id="report-form" class="form-stack"><label>Categoria<select name="category"><option>Resposta possivelmente incorreta</option><option>Imagem incorreta</option><option>Imagem ilegível</option><option>Enunciado incompleto</option><option>Alternativa duplicada</option><option>Alternativa incorreta</option><option>Erro de formatação</option><option>Explicação incorreta</option><option>Vestibular/ano incorreto</option><option>Outro</option></select></label><label>Descreva o problema<textarea name="description" rows="5" maxlength="2000" required placeholder="Conte o que você encontrou"></textarea></label><button class="primary" type="submit">Enviar reporte</button></form>`);return;}
 if(action==='support-form'){openModal(`<button class="modal-close icon-button" data-action="close-modal" aria-label="Fechar">×</button><span class="eyebrow modal-eyebrow">SUPORTE FIXOU</span><h2 id="modal-title">Como podemos ajudar?</h2><form id="support-form" class="form-stack"><label>Nome<input name="name" maxlength="80" value="${escapeHTML(state.profile?.name||'')}" required></label><label>E-mail<input name="email" type="email" maxlength="160" placeholder="seu@email.com" required></label><label>Categoria<select name="category"><option>Problema técnico</option><option>Problema com questão</option><option>Erro em resposta</option><option>Erro em imagem</option><option>Conta</option><option>Sugestão</option><option>Outro</option></select></label><label>Assunto<input name="subject" maxlength="120" required></label><label>Mensagem<textarea name="message" rows="5" maxlength="2000" required></textarea></label><button class="primary" type="submit">Enviar mensagem</button></form>`);return;}
 if(action==='search-map'){ui.mapSearch=id;ui.mapDiscipline='';go('map');return;}
 if(action==='go-train'){go('train');return;}
 if(action==='go-home'){go('home');return;}
 if(action==='go-errors'){go('errors');return;}
 if(action==='cards-home'){flash=null;go('cards');return;}
 if(action==='start-cards'){startCards(id);return;}
 if(action==='card'){closeModal();startCards('one',id);return;}
 if(action==='reveal-card'){if(flash){flash.revealed=true;render();}return;}
 if(action==='rate-card'){rateCard(id);return;}
 if(action==='chart-period'){ui.chartCount=Number(id)===30?30:7;render();return;}
 if(action==='favorite-training'){ui.filters={status:'favorites'};launch('practice',ui.filters);return;}
 if(action==='export'){downloadText('fuvest-mastery-backup-'+todayKey()+'.json',exportState(state));toast('Backup exportado. Guarde este arquivo.');return;}
 if(action==='download-curriculum'){downloadText('fuvest-2027-mapa-curricular.json',JSON.stringify(CURRICULUM,null,2));return;}
 if(action==='recover-save'){confirmAction('Começar um novo perfil local?','Exporte o progresso desta sessão antes de continuar. O arquivo local anterior será substituído.',()=>{storageBlocked=false;saveProgress();render();},'Continuar e salvar');return;}
}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;event.preventDefault();try{handleAction(el.dataset.action,el.dataset.id,el);}catch(error){console.error(error);toast('Não conseguimos concluir esta ação. Seu progresso já salvo foi mantido.');}});
document.addEventListener('input',event=>{if(event.target.id==='written-answer'&&session&&!session.feedback){session.draft.text=event.target.value;updateDraft();}});
document.addEventListener('change',event=>{
 const el=event.target;
 if(el.id==='avatar-file'&&el.files[0]){const file=el.files[0];if(file.size>5*1024*1024){toast('A imagem é muito grande. Escolha uma foto menor.');return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Escolha uma imagem JPG, PNG ou WEBP.');return;}file.arrayBuffer().then(bytes=>api('/api/avatar',{method:'PUT',body:bytes,headers:{'content-type':file.type}})).then(r=>{account.user={...account.user,hasAvatar:true,avatarVersion:r.avatarVersion};render();toast('Foto de perfil atualizada.');}).catch(e=>toast(e.message));return;}
 if(el.dataset.setting){let value=el.type==='checkbox'?el.checked:el.value;if(el.dataset.setting==='dailyCount'&&value==='custom'){const asked=Number(window.prompt('Quantas questões por dia?',String(state.settings.dailyCustom||50)));if(!Number.isInteger(asked)||asked<5||asked>200)return;value=asked;}if(el.dataset.setting==='dailyCount'||el.dataset.setting==='dailyMinutes')value=Number(value);if(el.dataset.setting==='fontScale')value=Number(value);state.settings[el.dataset.setting]=value;if(el.dataset.setting==='dailyCount')state.settings.dailyCustom=value;applyPreferences();saveProgress();render();toast('Preferência salva.');return;}
 if(el.dataset.sessionSubject){const id=el.dataset.sessionSubject,subjects=new Set(ui.sessionBuilder.subjects||[]),topics=new Set(ui.sessionBuilder.topics||[]);if(el.checked){subjects.add(id);sessionTopicKeys(BANK,[id]).forEach(key=>topics.add(key));}else{subjects.delete(id);sessionTopicKeys(BANK,[id]).forEach(key=>topics.delete(key));}const next=[...subjects],validTopics=new Set(sessionTopicKeys(BANK,next));ui.sessionBuilder=cleanSessionBuilder(BANK,{...ui.sessionBuilder,subjects:next,topics:[...topics].filter(key=>validTopics.has(key))});render();}
 else if(el.dataset.sessionTopic){const key=decodeURIComponent(el.dataset.sessionTopic),topics=new Set(ui.sessionBuilder.topics||[]);if(el.checked)topics.add(key);else topics.delete(key);ui.sessionBuilder={...ui.sessionBuilder,topics:[...topics]};render();}
 else if(el.dataset.sessionDifficulty){const n=Number(el.dataset.sessionDifficulty),difficulties=new Set(ui.sessionBuilder.difficulties||[]);if(el.checked)difficulties.add(n);else difficulties.delete(n);ui.sessionBuilder={...ui.sessionBuilder,difficulties:[...difficulties].sort((a,b)=>a-b)};render();}
 else if(el.dataset.sessionQuantity){ui.sessionBuilder={...ui.sessionBuilder,quantity:SESSION_QUANTITIES.includes(el.value==='all'?'all':Number(el.value))?(el.value==='all'?'all':Number(el.value)):20};render();}
 else if(el.dataset.filter){const key=el.dataset.filter;ui.filters[key]=el.value;if(key==='discipline'){ui.filters.topic='';ui.filters.subtopic='';}if(key==='topic')ui.filters.subtopic='';render();}
 else if(el.dataset.cardFilter){ui.cardFilters[el.dataset.cardFilter]=el.value;if(el.dataset.cardFilter==='discipline')ui.cardFilters.topic='';render();}
 else if(el.dataset.match!==undefined&&session&&!session.feedback){session.draft.match[Number(el.dataset.match)]=el.value===''?-1:Number(el.value);updateDraft();}
 else if(el.id==='error-filter'){ui.errorFilter=el.value;render();}
 else if(el.id==='map-discipline'){ui.mapDiscipline=el.value;render();}
 else if(el.id==='book-status'){state.books[el.dataset.book]=el.value;saveProgress();toast('Andamento da leitura salvo.');}
 else if(el.id==='import-file'&&el.files[0]){const file=el.files[0];if(file.size>15000000){toast('Arquivo muito grande. Escolha um backup de até 15 MB.');return;}file.text().then(raw=>{try{pendingImport=importState(raw);confirmAction('Importar este progresso?',`${escapeHTML(pendingImport.profile?.name||'Perfil sem nome')} · ${pendingImport.history.length} respostas · ${pendingImport.xp} XP. Seu progresso local será substituído pelo backup.`,()=>{state=pendingImport;session=state.activeSession;flash=null;storageBlocked=false;saveProgress();render();toast('Progresso importado com sucesso.');},'Importar backup');}catch(error){toast(error.message);el.value='';}}).catch(()=>toast('Não foi possível ler o arquivo.'));}
});
document.addEventListener('submit',event=>{
 const form=event.target;if(!['profile-form','onboarding-form','map-search-form','global-search-form','support-form','report-form','login-form','register-form','forgot-form','reset-form','password-form','suggestion-form'].includes(form.id))return;event.preventDefault();const data=new FormData(form);
 if(form.id==='login-form'||form.id==='register-form'){const password=String(data.get('password')||'');if(form.id==='register-form'&&password!==String(data.get('confirmPassword')||'')){toast('As senhas não coincidem.');return;}api(form.id==='login-form'?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify({name:data.get('name'),email:data.get('email'),password})}).then(async r=>{account.user=r.user;state.profile={...state.profile,name:r.user.name,createdAt:state.profile?.createdAt||r.user.createdAt};await hydrateProgress();go('home');toast(form.id==='login-form'?'Bem-vindo de volta.':'Sua conta FIXOU foi criada.');}).catch(e=>toast(e.message));return;}
 if(form.id==='forgot-form'){api('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email:data.get('email')})}).then(r=>toast(r.message)).catch(e=>toast(e.message));return;}
 if(form.id==='reset-form'){api('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token:data.get('token'),password:data.get('password')})}).then(()=>{go('login');toast('Senha alterada. Entre novamente.');}).catch(e=>toast(e.message));return;}
 if(form.id==='password-form'){api('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:data.get('currentPassword'),newPassword:data.get('newPassword')})}).then(()=>{form.reset();toast('Senha alterada.');}).catch(e=>toast(e.message));return;}
 if(form.id==='suggestion-form'){api('/api/suggestions',{method:'POST',body:JSON.stringify({category:data.get('category'),message:data.get('message')})}).then(()=>{form.reset();toast('Sugestão enviada. Obrigado!');}).catch(e=>toast(e.message));return;}
 if(form.id==='report-form'){const q=questionById(BANK,modalElement.dataset.reportQuestion),c=q&&conceptById(BANK,q.conceptId);if(!q||!c)return;const raw=String(data.get('category')||''),reason=raw.includes('Resposta')?'Gabarito':raw.includes('Imagem')?'Imagem':raw.includes('Enunciado')?'Enunciado':raw.includes('Alternativa')?'Alternativas':raw.includes('Explicação')?'Explicação':'Outro';api('/api/reports',{method:'POST',body:JSON.stringify({questionId:q.id,subjectId:c.discipline,topicId:c.id,reason,comment:data.get('description')})}).then(()=>{closeModal();toast('Reporte enviado. Obrigado por ajudar o FIXOU.');}).catch(e=>toast(e.message));return;}
 if(form.id==='support-form'){const ticket={report_id:'sup-'+uid(),user_id:state.profile?.name||'local',nome:String(data.get('name')||''),email:String(data.get('email')||''),categoria:String(data.get('category')||''),assunto:String(data.get('subject')||''),mensagem:String(data.get('message')||''),status:'Enviando',created_at:new Date().toISOString()};try{const key='fixou:support:v1',items=JSON.parse(localStorage.getItem(key)||'[]');items.push(ticket);localStorage.setItem(key,JSON.stringify(items));}catch{}closeModal();toast('Enviando sua mensagem ao suporte…');fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ticket)}).then(async response=>{let result={};try{result=await response.json();}catch{}if(!response.ok)throw new Error(result.error||'Não foi possível enviar agora.');try{const key='fixou:support:v1',items=JSON.parse(localStorage.getItem(key)||'[]'),saved=items.find(item=>item.report_id===ticket.report_id);if(saved){saved.status='Enviado';saved.sent_at=new Date().toISOString();saved.provider_id=result.id||null;localStorage.setItem(key,JSON.stringify(items));}}catch{}toast('Mensagem enviada para o suporte FIXOU.');}).catch(error=>{toast(`${error.message} Use o e-mail fixouestudos@gmail.com para enviar agora.`);});return;}
 if(form.id==='profile-form'||form.id==='onboarding-form'){const name=String(data.get('name')||'').trim();if(!name){toast('Digite seu nome para continuar.');return;}state.profile={...state.profile,name:name.slice(0,40),goal:String(data.get('goal')||'').trim().slice(0,100),createdAt:state.profile?.createdAt||Date.now()};if(data.has('dailyCount'))state.settings.dailyCount=Number(data.get('dailyCount'));saveProgress();if(form.id==='profile-form')api('/api/profile',{method:'PATCH',body:JSON.stringify({name})}).then(r=>{account.user=r.user;render();toast('Perfil salvo e sincronizado.');}).catch(e=>toast(e.message));else{const next=afterProfile;afterProfile=null;closeModal();render();next?.();}}
 if(form.id==='map-search-form'){ui.mapSearch=String(data.get('query')||'');render();}
 if(form.id==='global-search-form'){ui.searchTerm=String(data.get('query')||'');render();}
});
document.addEventListener('keydown',event=>{const editing=/INPUT|TEXTAREA|SELECT/.test(event.target.tagName);if(event.key==='/'&&!editing&&!modalElement.open){event.preventDefault();go('search');setTimeout(()=>document.querySelector('#global-search')?.focus(),0);}if(event.key==='Enter'&&event.target.id==='written-answer'){event.preventDefault();submitAnswer();}if(event.key==='Escape'&&ui.sidebarOpen){ui.sidebarOpen=false;render();}});
window.addEventListener('hashchange',()=>{readRoute();ui.sidebarOpen=false;if(ui.route==='admin'&&account.user&&['owner','admin'].includes(account.user.role)){adminData=null;api('/api/admin/overview?days='+ui.adminPeriod).then(r=>{adminData=r.data;render();}).catch(e=>toast(e.message));}render();window.scrollTo(0,0);});
window.addEventListener('pagehide',()=>saveProgress());
document.addEventListener('visibilitychange',()=>{lastTick=Date.now();if(document.hidden)saveProgress();});
window.addEventListener('storage',event=>{if(event.key!==SAVE_KEY)return;const latest=loadState();if(!latest.blocked){state=latest.state;session=state.activeSession;render();toast('Progresso atualizado por outra aba.');}});
setInterval(()=>{const now=Date.now(),dt=clamp((now-lastTick)/1000,0,2);lastTick=now;if(session&&!session.finished){if(session.endsAt&&now>=session.endsAt){complete();if(ui.route!=='quiz')toast('Relâmpago concluído. Seu recorde foi salvo.');return;}const clock=document.querySelector('#lightning-clock');if(clock)clock.textContent=formatTime((session.endsAt-now)/1000);if(ui.route==='quiz'&&!document.hidden&&!modalElement.open&&!session.feedback){session.questionSeconds=(session.questionSeconds||0)+dt;const timer=document.querySelector('#question-time');if(timer)timer.textContent=formatTime(session.questionSeconds)+' pensando';if(Math.floor(session.questionSeconds)%5===0)saveProgress();}}if(flash&&ui.route==='cards'&&!document.hidden&&!modalElement.open)flash.seconds+=dt;},1000);
readRoute();if(session?.endsAt&&Date.now()>=session.endsAt)finishSession(state,session);render();api('/api/auth/session').then(async r=>{account={loading:false,user:r.user};if(r.user){state.profile={...state.profile,name:r.user.name,createdAt:state.profile?.createdAt||r.user.createdAt};await hydrateProgress();if(ui.route==='admin'&&['owner','admin'].includes(r.user.role)){const result=await api('/api/admin/overview?days='+ui.adminPeriod);adminData=result.data;}}render();if(loaded.warning)toast(loaded.warning);}).catch(()=>{account={loading:false,user:null};render();});
