import {SUBJECTS,EXAM_CONFIG,PHYSICS_AREA_ORDER} from './config.js';
import {escapeHTML,normalize,formatDate,sum} from './utils.js';
import {masteryValue,conceptWeakness} from './mastery.js';
import {titleBlock,empty,button,errorCard,subjectById,conceptLine,questionCard,favorite,sourceTrail,safeLink,bar} from './components.js';
export function errorsScreen({state,bank,curriculum,errorFilter}){
 const all=Object.values(state.errors),active=all.filter(e=>!e.resolved),falseCount=active.filter(e=>e.falseConfidence).length;
 const selected=all.filter(e=>errorFilter==='all'||errorFilter==='resolved'?errorFilter==='all'||e.resolved:!e.resolved).sort((a,b)=>Number(b.falseConfidence)-Number(a.falseConfidence)||b.lastAt-a.lastAt);
 return `${titleBlock('DÚVIDAS VIRAM DIREÇÃO','Cofre dos erros','Cada erro guarda uma pista. Vamos usar a sua para aprender melhor.',`<button class="primary" data-action="start" data-id="weak" ${active.length?'':'disabled'}>Eliminar fraquezas →</button>`)}<div class="vault-summary"><div><strong>${active.length}</strong><span>questões a revisar</span></div><div><strong>${falseCount}</strong><span>erros com alta confiança</span></div><div><strong>${all.filter(e=>e.resolved).length}</strong><span>questões superadas</span></div></div><div class="row section-title"><h2>Aprender com o que passou</h2><label class="sr-only" for="error-filter">Exibir erros</label><select id="error-filter"><option value="active" ${errorFilter==='active'?'selected':''}>A revisar</option><option value="resolved" ${errorFilter==='resolved'?'selected':''}>Superados</option><option value="all" ${errorFilter==='all'?'selected':''}>Todos</option></select></div><div class="error-list">${selected.map(e=>errorCard(state,bank,curriculum,e)).join('')||empty(active.length?'Nenhum erro neste filtro':'Nenhuma dúvida fica para trás','Os erros aparecem aqui automaticamente, junto da explicação e da confiança que você marcou.','go-train','Começar um treino')}</div><p class="footnote">“Falso domínio” significa erro com alta confiança. Para superar uma fraqueza, acerte duas variações do conceito sem chutar.</p>`;
}
function bankTrackSummary(bank){
 const tracks=[
  {label:'Biologia · evolução e ecologia',detail:'Evolução biológica, especiação, ecologia e biomas.',count:bank.questions.filter(q=>q.discipline==='biologia').length,kind:'discipline',value:'biologia',symbol:'⌁'},
  {label:'Geometria plana',detail:'Áreas, circunferência, polígonos, coordenadas e transformações.',count:bank.questions.filter(q=>q.contentTrack==='geometria-plana').length,kind:'topic',value:'Geometria plana',symbol:'◇'},
  {label:'Energia, dinâmica e trabalho',detail:'Leis de Newton, energia, impulso, potência e torque.',count:bank.questions.filter(q=>q.contentTrack==='fisica-foco').length,kind:'topic',value:'Energia, dinâmica e trabalho',symbol:'↯'},
  {label:'Geomorfologia',detail:'Processos internos e externos, relevo, erosão e paisagens.',count:bank.questions.filter(q=>q.contentTrack==='geomorfologia').length,kind:'topic',value:'Geomorfologia',symbol:'◎'}
 ];
 return `<section class="panel bank-track-summary"><div class="section-title"><div><h2>Novas trilhas ligadas ao programa</h2><p class="meta">O mapa oficial agora aponta diretamente para as questões adicionadas ao banco.</p></div><span>${bank.questions.length} questões no banco</span></div><div class="subject-grid">${tracks.map(t=>`<article class="subject-card bank-track-card"><span class="subject-symbol">${t.symbol}</span><h3>${t.label}</h3><p>${t.detail}</p><strong class="track-count">${t.count} questões</strong><button class="text-button" data-action="track" data-id="${escapeHTML(t.kind+'|'+t.value)}">Abrir no treino →</button></article>`).join('')}</div></section>`;
}
function bankHierarchy(bank){
 return `<section class="panel bank-hierarchy"><div class="section-title"><div><h2>Banco por disciplina, área e tópico</h2><p class="meta">Abra uma disciplina para ver as áreas e entrar diretamente no treino.</p></div><span>${bank.concepts.length} conceitos</span></div><div class="bank-discipline-list">${SUBJECTS.map(s=>{const questions=bank.questions.filter(q=>q.discipline===s.id),topics=[...new Set(questions.map(q=>q.topic))].sort((a,b)=>s.id==='fisica'?PHYSICS_AREA_ORDER.indexOf(a)-PHYSICS_AREA_ORDER.indexOf(b):a.localeCompare(b,'pt-BR'));if(!topics.length)return '';return `<details class="bank-discipline" ${s.id==='fisica'?'open':''}><summary><span class="subject-symbol" style="--subject-color:${s.color}">${s.icon}</span><span><strong>${s.name}</strong><small>${topics.length} áreas · ${questions.length} questões</small></span><span class="tree-count">${questions.length}</span></summary><div class="bank-topic-list">${topics.map(topic=>{const concepts=bank.concepts.filter(c=>c.discipline===s.id&&c.topic===topic&&questions.some(q=>q.conceptId===c.id));const count=questions.filter(q=>q.topic===topic).length;return `<details class="bank-topic"><summary><span><strong>${escapeHTML(topic)}</strong><small>${concepts.length} tópicos · ${count} questões</small></span><span class="tag">${count}</span></summary><div class="bank-subtopic-list">${concepts.map(c=>{const qCount=questions.filter(q=>q.conceptId===c.id).length;return `<button class="bank-subtopic" data-action="track" data-id="concept|${escapeHTML(c.id)}"><span><strong>${escapeHTML(c.subtopic)}</strong><small>${qCount} questões · abrir treino filtrado</small></span><span>→</span></button>`;}).join('')}</div></details>`}).join('')}</div></details>`}).join('')}</div></section>`;
}
export function mapScreen({state,bank,curriculum,mapSearch,mapDiscipline}){
 const litIds=new Set(['of-046','of-103','of-104','of-105','of-106','of-107']);
 const list=curriculum.objects.filter(o=>o.kind==='object');
 const occurrences=list.length,unique=new Set(list.map(o=>o.canonicalId)).size;
 const search=normalize(mapSearch||'');
 const subjects=SUBJECTS.filter(s=>!mapDiscipline||s.id===mapDiscipline);
 const content=subjects.map(s=>{const all=list.filter(o=>s.id==='literatura'?litIds.has(o.id):o.discipline===s.id&&!(s.id==='portugues'&&litIds.has(o.id)));const filtered=all.filter(o=>!search||normalize(o.text+' '+o.skillText+' '+s.name).includes(search));if(!filtered.length)return '';const uniqueObjects=filtered.filter((o,i)=>filtered.findIndex(x=>x.canonicalId===o.canonicalId)===i);
 return `<details class="curriculum-subject" ${search||mapDiscipline?'open':''}><summary><span class="subject-symbol" style="color:${s.color}">${s.icon}</span><span><strong>${s.name}</strong><small>${uniqueObjects.length} objetos · ${all[0]?.area||'Linguagens e suas Tecnologias'}</small></span><span class="tree-count">${uniqueObjects.length}</span></summary><div class="curriculum-body">${s.id==='literatura'?'<p class="note">Trilha pedagógica extraída de Língua Portuguesa, sem acrescentar objetos ao programa oficial.</p>':''}${uniqueObjects.map(o=>{const related=bank.concepts.filter(c=>c.officialIds.includes(o.id));const score=related.length?Math.min(...related.map(c=>masteryValue(state.concepts[c.id],state.reviews[c.id]))):0;const title=o.text.length>108?o.text.slice(0,105)+'…':o.text;const refs=all.filter(x=>x.canonicalId===o.canonicalId);return `<details class="curriculum-object"><summary><span><strong>${escapeHTML(title)}</strong><small>${o.competency?'Competência '+o.competency+' · ':''}Habilidade ${o.block} · p. ${[...new Set(refs.map(r=>r.page))].join(', ')}</small></span><span class="tag ${related.length?'':'muted-tag'}">${related.length?score+'%':'Sem exercício'}</span></summary><div><p>${escapeHTML(o.text)}</p>${o.skillText?`<details class="skill-details"><summary>Habilidades e conteúdos associados</summary><p>${escapeHTML(o.skillText)}</p></details>`:''}${related.length?related.map(c=>conceptLine(state,c)).join(''):'<p class="note">Este objeto faz parte do programa oficial. O banco atual ainda não tem um exercício específico para ele.</p>'}<a class="source-link" href="${curriculum.sourceUrl}#page=${o.page}" target="_blank" rel="noopener">Consultar página ${o.page} do programa oficial ↗</a></div></details>`;}).join('')}</div></details>`;}).join('');
 return `${titleBlock('PROGRAMA OFICIAL · 53 PÁGINAS','O caminho inteiro, à vista','Explore os objetos de conhecimento e acompanhe os conceitos que já praticou.',button('Baixar mapa curricular ↓','download-curriculum','','secondary'))}<div class="curriculum-note"><span>✓</span><p><strong>${occurrences} ocorrências de objetos · ${unique} textos distintos</strong><br>Extração integral do programa de 2027. Competências repetem alguns objetos; preservamos essas referências. O banco inicial cobre ${bank.concepts.length} conceitos, sem equivaler ao programa completo.</p></div>${bankTrackSummary(bank)}${bankHierarchy(bank)}<form class="search-form" id="map-search-form"><label class="sr-only" for="map-search">Buscar no programa</label><input id="map-search" name="query" placeholder="Busque um objeto, tema ou habilidade…" value="${escapeHTML(mapSearch||'')}"><label class="sr-only" for="map-discipline">Disciplina no mapa</label><select id="map-discipline"><option value="">Todas as disciplinas</option>${SUBJECTS.map(s=>`<option value="${s.id}" ${mapDiscipline===s.id?'selected':''}>${s.name}</option>`).join('')}</select><button class="primary" type="submit">Buscar</button></form><div class="curriculum-tree">${content||empty('Nenhum objeto encontrado','Experimente um termo mais amplo, como energia, cultura ou linguagem.')}</div><details class="panel writing-note"><summary>Redação e estrutura oficial de 2027</summary><p>O programa inclui quatro orientações para a proposta de redação (p. 18):</p><ul>${curriculum.objects.filter(o=>o.kind==='writing').map(o=>`<li>${escapeHTML(o.text)}</li>`).join('')}</ul><p>1ª fase: 80 questões, cinco alternativas e até cinco horas. 2ª fase: dois dias de até quatro horas; 10 questões de Português e redação no primeiro, 12 questões de duas a quatro disciplinas no segundo.</p><p>Esta primeira versão oferece treino e memorização. Simulado completo, redação e avaliação por IA são etapas futuras.</p><a class="source-link" href="${EXAM_CONFIG.sources[1].url}" target="_blank" rel="noopener">Guia de Provas FUVEST 2027 ↗</a></details>`;
}
export function booksScreen({state,bank,books,bookId}){
 const colors=['#705179','#4b7482','#a5784c','#966362','#527560','#577b93','#917b53','#876d91','#627b63'];
 const book=books.find(b=>b.id===bookId);
 if(book){const c=bank.concepts.find(c=>c.id==='lit-'+book.id),status=state.books[book.id]||'not-started';return `<a class="back-link" href="#books">← Todas as leituras</a>${titleBlock('LEITURA OBRIGATÓRIA · '+book.year,escapeHTML(book.title),escapeHTML(book.author))}<div class="book-layout"><aside class="book-side panel"><span class="eyebrow">SUA LEITURA</span><label for="book-status">Andamento<select id="book-status" data-book="${book.id}">${[['not-started','Ainda não comecei'],['reading','Estou lendo'],['finished','Leitura concluída']].map(([v,t])=>`<option value="${v}" ${status===v?'selected':''}>${t}</option>`).join('')}</select></label><p class="note">O andamento da leitura é um registro pessoal e não aumenta seu domínio automaticamente.</p>${c?button('Praticar a obra →','variation',c.id,'primary')+button('Revisar flashcard','card',c.id):''}<a class="source-link" href="${safeLink(book.sourceUrl)}" target="_blank" rel="noopener">Aprofundar na análise da USP ↗</a></aside><article class="book-notes">${[['Contexto',book.context],['Estrutura e composição',book.structure],['Quem conta a história',book.narrator],['Personagens',book.characters.join(' · ')],['Temas centrais',book.themes.join(' · ')],['Linguagem e estilo',book.style],['Uma chave de leitura',book.interpretation],['Diálogo entre obras',book.comparison]].filter(([,v])=>v).map(([t,v])=>`<section class="panel"><h2>${t}</h2><p>${escapeHTML(v)}</p></section>`).join('')}<p class="footnote">Ficha autoral de estudo apoiada em análise acadêmica. Interpretações não são gabaritos oficiais nem substituem a leitura integral da obra.</p></article></div>${c?`<div class="section-title"><h2>Do texto ao raciocínio</h2></div><div class="question-list">${bank.questions.filter(q=>q.conceptId===c.id).map(q=>questionCard(state,bank,q)).join('')}</div>`:''}`;}
 return `${titleBlock('NOVE AUTORAS. MUITAS FORMAS DE VER O MUNDO','Sua biblioteca de leituras','Lista confirmada no Guia de Provas FUVEST 2027, página 15.')}<div class="book-grid">${books.map((b,i)=>`<a class="book-card" href="#books/${b.id}" style="--book-color:${colors[i]}"><div class="book-title-panel"><span>${String(i+1).padStart(2,'0')} <span>FUVEST 2027</span></span><h2>${escapeHTML(b.title)}</h2><p>${escapeHTML(b.author)}</p><small>${b.year}</small></div><div class="book-card-bottom"><span class="tag">${state.books[b.id]==='finished'?'✓ Lido':state.books[b.id]==='reading'?'Em leitura':'Para descobrir'}</span><span>Abrir estudo →</span></div></a>`).join('')}</div><p class="footnote">As fichas, questões e flashcards são autorais. As obras protegidas não são reproduzidas integralmente.</p>`;
}
export function favoritesScreen({state,bank}){
 const questions=bank.questions.filter(q=>state.favorites.includes('q:'+q.id)&&!q.needsReview),cards=bank.concepts.filter(c=>state.favorites.includes('c:'+c.id)&&c.flashcard&&!c.flashcard.needsReview),explanations=bank.questions.filter(q=>state.favorites.includes('e:'+q.id)&&!q.needsReview);
 if(!questions.length&&!cards.length&&!explanations.length)return `${titleBlock('GUARDE O QUE IMPORTA','Seus favoritos','Questões, explicações e cartões para revisitar com facilidade.')}${empty('Seu espaço de boas descobertas','Toque na estrela de uma questão, flashcard ou explicação para guardar aqui.','go-train','Explorar questões')}`;
 return `${titleBlock('GUARDE O QUE IMPORTA','Seus favoritos','Tudo o que você escolheu para revisitar.')}${questions.length?`<div class="section-title"><h2>Questões · ${questions.length}</h2>${button('Treinar favoritas →','favorite-training','','text-button')}</div><div class="question-list">${questions.map(q=>questionCard(state,bank,q)).join('')}</div>`:''}${cards.length?`<div class="section-title"><h2>Flashcards · ${cards.length}</h2></div><div class="flash-grid">${cards.map(c=>`<article class="flash-preview"><div class="row"><span class="tag">${subjectById(c.discipline).name}</span>${favorite(state,'c',c.id)}</div><h3>${escapeHTML(c.flashcard.front)}</h3>${button('Revisar →','card',c.id,'text-button')}</article>`).join('')}</div>`:''}${explanations.length?`<div class="section-title"><h2>Explicações · ${explanations.length}</h2></div>${explanations.map(q=>`<article class="panel saved-explanation"><div class="row"><h3>${escapeHTML(q.subtopic)}</h3>${favorite(state,'e',q.id)}</div><p>${escapeHTML(q.explanation)}</p></article>`).join('')}`:''}`;
}
export function searchScreen({state,bank,curriculum,searchTerm}){
 const term=normalize(searchTerm||''),concepts=term?bank.concepts.filter(c=>normalize(c.subtopic+' '+c.topic+' '+c.summary).includes(term)):[],questions=term?bank.questions.filter(q=>!q.needsReview&&normalize(q.prompt+' '+q.explanation+' '+(q.tags||[]).join(' ')).includes(term)):[],objects=term?curriculum.objects.filter(o=>normalize(o.text+' '+o.skillText).includes(term)):[];
 const errors=Object.values(state.errors).filter(e=>concepts.some(c=>c.id===e.conceptId));
 return `${titleBlock('SIGA SUA CURIOSIDADE','Busque uma ideia','Encontre conceitos, questões, cartões e erros relacionados.')}<form class="search-form" id="global-search-form"><label class="sr-only" for="global-search">Pesquisar conteúdo</label><input id="global-search" name="query" placeholder="Ex.: Arrhenius, cidadania, Geografia…" value="${escapeHTML(searchTerm||'')}"><button class="primary">Buscar</button></form>${!term?empty('Por onde vamos explorar?','Digite um conceito ou tema para pesquisar todo o banco e o programa oficial.'):`<div class="search-counts"><span>${concepts.length} conceitos</span><span>${questions.length} questões</span><span>${objects.length} objetos oficiais</span><span>${errors.length} erros relacionados</span></div>${concepts.length?`<div class="section-title"><h2>Conceitos, domínio e flashcards</h2></div><div class="panel">${concepts.map(c=>conceptLine(state,c)).join('')}</div>`:''}${questions.length?`<div class="section-title"><h2>Questões e explicações</h2></div><div class="question-list">${questions.slice(0,15).map(q=>questionCard(state,bank,q)).join('')}</div>`:''}${errors.length?`<div class="section-title"><h2>No seu Cofre dos Erros</h2></div>${errors.slice(0,5).map(e=>errorCard(state,bank,curriculum,e)).join('')}`:''}${objects.length?`<div class="section-title"><h2>No programa oficial</h2>${button('Ver todos no mapa →','search-map',searchTerm,'text-button')}</div><div class="panel">${objects.slice(0,6).map(o=>`<p class="search-official"><span class="meta">${subjectById(o.discipline).name} · p. ${o.page}</span><br>${escapeHTML(o.text)}</p>`).join('')}</div>`:''}${!concepts.length&&!questions.length&&!objects.length?empty('Nenhum resultado','Experimente outro termo ou uma parte do nome do conceito.'):''}`}`;
}
