import {SUBJECTS,EXAM_CONFIG,DIFFICULTIES,MODE_NAMES} from './config.js';
import {escapeHTML,formatNumber,formatDate,formatTime,normalize,sum} from './utils.js';
import {studyStats} from './statistics.js';
import {profileLevel,ACHIEVEMENTS} from './gamification.js';
import {masteryValue,officialMastery} from './mastery.js';
import {titleBlock,bar,empty,button,subjectById,subjectMastery,conceptLine} from './components.js';
import {activityChart} from './screens.js';
export function statsScreen({state,bank,curriculum,chartCount}){
 const stats=studyStats(state,bank.concepts),studied=bank.concepts.filter(c=>state.concepts[c.id]),overall=officialMastery(state,bank.concepts,curriculum.objects);
 return `${titleBlock('O QUE SUA PRÁTICA REVELA','Veja o conhecimento crescer','Seu nível mede dedicação. O domínio estima o que você consegue recuperar e aplicar.')}<div class="stat-grid">${[['Questões respondidas',formatNumber(stats.total),`${stats.correct} acertos · ${stats.wrong} erros`],['Aproveitamento',stats.accuracy+'%',stats.total?'Todas as tentativas':'Ainda sem respostas'],['Tempo em prática',stats.seconds<3600?Math.floor(stats.seconds/60)+' min':(stats.seconds/3600).toFixed(1)+' h','Respostas enviadas e revisões'],['Revisões concluídas',formatNumber(stats.reviews),`${stats.streak} ${stats.streak===1?'dia seguido':'dias seguidos'}`]].map(([label,value,note])=>`<article class="stat-card"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`).join('')}</div>
 <section class="panel chart-panel"><div class="section-title"><div><h2>Constância se constrói</h2><p class="meta">Questões e revisões por dia</p></div><div class="segmented" aria-label="Período do gráfico"><button data-action="chart-period" data-id="7" class="${chartCount===7?'selected':''}" aria-pressed="${chartCount===7}">7 dias</button><button data-action="chart-period" data-id="30" class="${chartCount===30?'selected':''}" aria-pressed="${chartCount===30}">30 dias</button></div></div>${activityChart(state,chartCount)}</section>
 <section class="bottom-grid"><article class="panel"><div class="section-title"><h2>Domínio por disciplina</h2></div><p class="meta">Calculado sobre os conceitos disponíveis no banco inicial.</p><div class="mastery-list">${SUBJECTS.map(s=>{const m=subjectMastery(state,bank,s.id);return `<button class="discipline-stat" data-action="subject" data-id="${s.id}"><span>${s.name}</span>${bar(m,s.name)}<strong>${m}%</strong></button>`;}).join('')}</div></article><article class="panel"><div class="section-title"><h2>Além da taxa de acertos</h2></div><div class="insight-metric"><strong>${stats.falseConfidence}</strong><span>erros com alta confiança<br><small>Primeira prioridade nas revisões.</small></span></div><div class="insight-metric"><strong>${Math.round(stats.average)}<small>s</small></strong><span>tempo médio por resposta<br><small>Velocidade não substitui compreensão.</small></span></div><div class="insight-metric"><strong>${stats.studied}<small>/${bank.concepts.length}</small></strong><span>conceitos já praticados<br><small>O restante ainda não foi avaliado.</small></span></div><div class="insight-metric"><strong>${overall}<small>%</small></strong><span>índice conservador do programa<br><small>Objetos sem exercícios contam como não avaliados, com valor zero.</small></span></div><details><summary>Como o domínio é estimado?</summary><p>O cálculo combina acertos, dificuldade, tempo, confiança, variedade de questões, dias distintos, erros consecutivos e desempenho recente. A estimativa cai com o tempo sem revisão. Chutes não elevam o domínio acima de 35%; repetições corretas no mesmo dia não geram ganho adicional.</p><p>É um indicador pedagógico do aplicativo, não uma nota oficial, diagnóstico ou previsão de aprovação na FUVEST.</p></details></article></section>
 <div class="section-title"><h2>Domínio por assunto</h2></div><div class="panel">${studied.length?studied.sort((a,b)=>masteryValue(state.concepts[a.id],state.reviews[a.id])-masteryValue(state.concepts[b.id],state.reviews[b.id])).map(c=>conceptLine(state,c)).join(''):empty('Seu retrato começa na prática','Depois do primeiro treino, seus assuntos e prioridades aparecem aqui.','go-train','Começar a aprender')}</div>
 <div class="section-title"><h2>Suas últimas sessões</h2></div><div class="panel history-panel">${state.sessions.length?`<div class="table-scroll"><table><thead><tr><th>Treino</th><th>Data</th><th>Acertos</th><th>Tempo nas respostas</th><th>XP</th></tr></thead><tbody>${state.sessions.slice(-12).reverse().map(s=>`<tr><td>${MODE_NAMES[s.mode]||'Treino'}</td><td>${formatDate(s.finishedAt)}</td><td>${s.correct}/${s.total}</td><td>${formatTime(s.seconds)}</td><td>+${s.xp}</td></tr>`).join('')}</tbody></table></div>`:'<p class="soft-copy">As sessões concluídas aparecerão aqui. Cada resposta já é salva durante o treino.</p>'}</div>`;
}
export function profileScreen({state,bank,storageBlocked}){
 const level=profileLevel(state.xp),profile=state.profile||{name:'',goal:''};
 return `${titleBlock('UM ESPAÇO QUE É SEU','Sua jornada, do seu jeito','Ajuste o perfil, acompanhe suas conquistas e proteja seu progresso.')}<section class="profile-hero panel"><span class="avatar big">${escapeHTML(profile.name?profile.name.slice(0,1).toUpperCase():'M')}</span><div><h2>${escapeHTML(profile.name||'Vamos nos conhecer')}</h2><p>${escapeHTML(profile.goal||'Um passo de cada vez até a USP.')}</p><span class="tag">Nível ${level.level} · ${formatNumber(state.xp)} XP</span></div><div class="profile-level"><span>${level.current} / ${level.needed} XP para o próximo nível</span>${bar(level.percent,'Progresso para o próximo nível')}</div></section><div class="bottom-grid"><form class="panel form-stack" id="profile-form"><h2>Seu perfil</h2><label>Como você quer ser chamado?<input name="name" value="${escapeHTML(profile.name)}" maxlength="40" required placeholder="Seu nome" autocomplete="given-name"></label><label>Qual é o seu objetivo?<input name="goal" value="${escapeHTML(profile.goal||'')}" maxlength="100" placeholder="Ex.: Engenharia na USP"></label><label>Questões por treino diário<select name="dailyCount">${[10,20,30].map(n=>`<option value="${n}" ${state.settings.dailyCount===n?'selected':''}>${n} questões</option>`).join('')}</select></label><p class="note">Você pode interromper uma sessão e continuar depois. Um estudo curto já mantém sua sequência.</p><button class="primary" type="submit">Salvar perfil ✓</button></form><article class="panel form-stack"><h2>Seu progresso fica com você</h2><p>Salvamento automático neste navegador e neste endereço. Fechar a página mantém seus dados. Para trocar de dispositivo ou endereço, exporte um backup e importe no novo local.</p><div class="save-indicator ${storageBlocked?'save-error':''}"><span class="status-dot"></span>${storageBlocked?'Salvamento precisa de atenção':state.savedAt?'Último salvamento: '+new Date(state.savedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'Pronto para salvar seu primeiro estudo'}</div>${button('Exportar meu progresso ↓','export','','primary')}<label class="file-upload">Importar backup<input type="file" id="import-file" accept="application/json,.json"></label><p class="note">O backup inclui perfil, respostas, XP, domínio, revisões, favoritos e recordes. Guarde uma cópia antes de limpar os dados do navegador.</p>${storageBlocked?button('Continuar com um novo perfil','recover-save','','secondary'):''}</article></div>
 <div class="section-title"><h2>Marcos da sua caminhada</h2><span>${state.achievements.length} conquistas desbloqueadas</span></div><div class="achievement-grid">${ACHIEVEMENTS.map(a=>`<article class="achievement ${state.achievements.includes(a.id)?'unlocked':''}"><span>${a.symbol}</span><div><h3>${a.name}</h3><p>${a.description}</p><small>${state.achievements.includes(a.id)?'✓ Conquistado':'Em construção'}</small></div></article>`).join('')}</div>
 <div class="section-title"><h2>Transparência do conteúdo</h2></div><article class="panel source-panel"><p>Conteúdo curricular verificado em 06/09/2026. As questões e fichas são autorais, e a ordem das trilhas é pedagógica. Este aplicativo independente não é um produto oficial da FUVEST ou da USP.</p>${EXAM_CONFIG.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.title} ↗</a>`).join('')}<p class="note">O programa integral está no mapa. O banco atual tem ${bank.questions.length} questões e ${bank.concepts.length} conceitos; ele cobre uma seleção pedagógica ampla, sem substituir a leitura integral do edital.</p></article>`;
}
