import {SUBJECTS,QUESTION_TYPES,DIFFICULTIES} from './config.js';
import {escapeHTML,sum,formatNumber,normalize,relativeDue,formatDate} from './utils.js';
import {studyStats,chartDays} from './statistics.js';
import {profileLevel} from './gamification.js';
import {isDue,dueConcepts} from './reviews.js';
import {masteryValue,conceptWeakness} from './mastery.js';
import {matchesQuestion,dailyCounts} from './training.js';
import {titleBlock,bar,subjectTile,subjectById,subjectMastery,conceptLine,empty,button,questionCard,favorite,sourceTrail} from './components.js';
export function homeScreen({state,bank,curriculum}){
 const stats=studyStats(state,bank.concepts),level=profileLevel(state.xp),counts=dailyCounts(state,bank),due=dueConcepts(state,bank.concepts).length;
 const mastery=Math.round(sum(bank.concepts.map(c=>masteryValue(state.concepts[c.id],state.reviews[c.id])))/bank.concepts.length);
 const name=state.profile?.name?.split(' ')[0],weak=bank.concepts.filter(c=>state.concepts[c.id]).sort((a,b)=>conceptWeakness(state,b.id)-conceptWeakness(state,a.id)).slice(0,3);
 return `${titleBlock('SEU PRÓXIMO CAPÍTULO',name?`Bom ter você aqui, ${escapeHTML(name)}`:'Todo avanço começa aqui','Transforme o que você estuda em conhecimento que fica.',`<span class="pill">FUVEST 2027</span>`)}
 ${state.activeSession&&!state.activeSession.finished?`<div class="resume-banner"><span>Seu último treino está salvo.</span>${button('Continuar de onde parei →','resume','','text-button')}</div>`:''}
 <section class="hero-grid"><article class="today-card"><div class="eyebrow">TREINO DE HOJE <span class="live-tag">FEITO PARA VOCÊ</span></div><h2>Uma boa sessão.<br>Um passo mais perto.</h2><p>${stats.total?'Seu treino combina dúvidas, revisões e novos conceitos. Vamos continuar?':'Comece pelos fundamentos. Seu treino se ajusta conforme você aprende.'}</p><div class="session-chips"><span>▱ ${due} revisões pendentes</span><span>◇ ${stats.weak} pontos a fortalecer</span></div><button class="primary light" data-action="start" data-id="daily">Começar meu treino <span>→</span></button><div class="orbit" aria-hidden="true"><span>${String(level.level).padStart(2,'0')}<small>SEU NÍVEL<br>DE DEDICAÇÃO</small></span></div></article><article class="focus-card"><div class="eyebrow">DOMÍNIO DO BANCO INICIAL</div><div class="mastery-ring" style="--value:${mastery}"><div><strong>${mastery}<span>%</span></strong><small>${stats.studied} de ${bank.concepts.length} conceitos estudados</small></div></div><p>Acertos, confiança e retenção.<br>Seu nível de perfil é independente.</p><div class="card-foot"><span>Questões originais disponíveis</span><strong>${bank.questions.length}</strong></div></article></section>
 <section class="quick-stats"><div><span>Nível de dedicação</span><strong>${level.level}<small> ${formatNumber(state.xp)} XP</small></strong>${bar(level.percent,'XP para o próximo nível')}</div><div><span>Questões respondidas</span><strong>${stats.total}<small> ${stats.total?stats.accuracy+'% de acertos':'Sua jornada começa agora'}</small></strong></div><div><span>Novos conceitos</span><strong>${counts.new}<small> no banco inicial</small></strong></div><div><span>Próxima sessão</span><strong>${state.settings.dailyCount}<small> questões · pausas livres</small></strong></div></section>
 <div class="section-title"><h2>Escolha como avançar</h2><span>Aprender. Recordar. Consolidar.</span></div><section class="mode-grid"><a class="mode-card" href="#train"><span class="mode-icon purple">▷</span><div><h3>Quiz adaptativo</h3><p>Seu próximo desafio, na medida.</p></div><span>↗</span></a><a class="mode-card" href="#cards"><span class="mode-icon mint">▱</span><div><h3>Memorização</h3><p>Recorde antes de esquecer.</p></div><span>↗</span></a><a class="mode-card" href="#errors"><span class="mode-icon peach">⊞</span><div><h3>Cofre dos erros</h3><p>Encontre a raiz de cada dúvida.</p></div><span>↗</span></a></section>
 <div class="section-title"><h2>Seu universo de conhecimento</h2><a href="#map">Explorar o programa →</a></div><section class="subject-grid">${SUBJECTS.slice(0,8).map(s=>subjectTile(state,bank,s)).join('')}</section>
 <section class="bottom-grid"><article class="panel"><div class="section-title"><h2>Pequenos passos, todos os dias</h2><a href="#stats">Minha evolução →</a></div>${activityChart(state,7)}<p class="meta">Questões e revisões por dia. Uma sessão curta também conta.</p></article><article class="panel"><div class="section-title"><h2>Seu próximo foco</h2></div>${weak.length?weak.map(c=>conceptLine(state,c)).join(''):'<p class="soft-copy">Responda às primeiras questões para identificar o que merece mais atenção.</p><a class="text-button" href="#train">Encontrar meu ponto de partida →</a>'}</article></section>`;
}
export function activityChart(state,count=7){const days=chartDays(state,count),max=Math.max(5,...days.map(d=>d.answers+d.reviews));return `<div class="activity-chart ${count>7?'monthly':''}" role="img" aria-label="Atividade dos últimos ${count} dias: ${days.map(d=>`${d.key}: ${d.answers} questões, ${d.reviews} revisões`).join('; ')}">${days.map(d=>`<div class="chart-column"><div class="chart-track"><span title="${d.key}: ${d.answers} questões e ${d.reviews} revisões" style="height:${(d.answers+d.reviews)/max*100}%"><i>${d.answers+d.reviews||''}</i></span></div><small>${count>7?d.short:d.label}</small></div>`).join('')}</div>`;}
export function filterControls(bank,filters,prefix='filter'){
 const selected=(key,v)=>String(filters[key]||'')===String(v)?'selected':'';
 const topics=[...new Set(bank.concepts.filter(c=>!filters.discipline||c.discipline===filters.discipline).map(c=>c.topic))];
 const concepts=bank.concepts.filter(c=>(!filters.discipline||c.discipline===filters.discipline)&&(!filters.topic||c.topic===filters.topic));
 const select=(key,label,options)=>`<label>${label}<select data-filter="${key}" data-prefix="${prefix}" id="${prefix}-${key}"><option value="">Todos</option>${options.map(([v,t])=>`<option value="${escapeHTML(v)}" ${selected(key,v)}>${escapeHTML(t)}</option>`).join('')}</select></label>`;
 return `<div class="filter-grid">${select('discipline','Disciplina',SUBJECTS.map(s=>[s.id,s.name]))}${select('topic','Assunto',topics.map(t=>[t,t]))}${select('subtopic','Subassunto',concepts.map(c=>[c.id,c.subtopic]))}${select('difficulty','Dificuldade',[1,2,3,4].map(d=>[d,DIFFICULTIES[d]]))}${select('type','Tipo',Object.entries(QUESTION_TYPES))}${select('status','Seu histórico',[['wrong','Pontos fracos'],['new','Nunca vistas'],['due','Revisões vencidas'],['favorites','Favoritas']])}</div>`;
}
export function trainScreen({state,bank,filters}){
 const cb=Object.fromEntries(bank.concepts.map(c=>[c.id,c]));const matches=bank.questions.filter(q=>matchesQuestion(q,cb[q.conceptId],filters,state));
 return `${titleBlock('PRÁTICA QUE EVOLUI COM VOCÊ','Encontre o seu ritmo','Errou? Você recebe uma explicação e volta ao conceito por outro caminho.')}
 <section class="challenge-grid"><article class="challenge-card adaptive"><span class="mode-icon purple">▷</span><div><h2>Quiz adaptativo</h2><p>Dificuldade e seleção se ajustam ao seu desempenho.</p><span class="meta">20 questões · com feedback</span></div>${button('Começar →','start','adaptive','primary')}</article><article class="challenge-card lightning"><span class="mode-icon peach">ϟ</span><div><h2>Relâmpago</h2><p>60 segundos para exercitar a memória.</p><span class="meta">Recorde: ${state.records.lightning} acertos</span></div>${button('Desafiar →','start','lightning')}</article><article class="challenge-card survival"><span class="mode-icon mint">♡</span><div><h2>Sobrevivência</h2><p>Três vidas. Até onde seu raciocínio vai?</p><span class="meta">Recorde: ${state.records.survival} acertos</span></div>${button('Jogar →','start','survival')}</article></section>
 <div class="section-title"><h2>Monte seu treino</h2>${button('Limpar filtros','clear-filters','','text-button')}</div><section class="panel">${filterControls(bank,filters)}<div class="filter-footer"><span><strong>${matches.length}</strong> questões encontradas <span class="meta">· Originais, alinhadas à FUVEST 2027</span></span><button class="primary" data-action="start" data-id="practice" ${!matches.length?'disabled':''}>Treinar seleção →</button></div></section>
 <div class="section-title"><h2>Explore as questões</h2><span>${bank.questions.length} questões · ${bank.concepts.length} conceitos</span></div><div class="question-list">${matches.length?matches.slice(0,20).map(q=>questionCard(state,bank,q)).join(''):empty('Nenhuma questão nesta seleção','Experimente outra disciplina ou limpe os filtros.','clear-filters','Limpar filtros')}</div>${matches.length>20?`<p class="footnote">Mostrando 20 de ${matches.length}. Use os filtros para localizar um assunto; o treino usa toda a seleção.</p>`:''}`;
}
export function cardsScreen({state,bank,cardFilters,flash}){
 if(flash){const c=conceptByIdLocal(bank,flash.currentId);if(!c)return empty('Revisão concluída','Sua agenda foi atualizada.','cards-home','Ver meus cartões');const reveal=flash.revealed;return `${titleBlock('MEMORIZAÇÃO','Dê espaço para lembrar',`${flash.index+1} de ${flash.ids.length} cartões nesta sessão`,button('Encerrar revisão','cards-home','','secondary'))}<div class="flash-layout"><div class="flash-card ${reveal?'revealed':''}"><div class="row"><span class="tag">${subjectById(c.discipline).name} · ${escapeHTML(c.subtopic)}</span>${favorite(state,'c',c.id)}</div><div class="flash-content"><span class="eyebrow">${reveal?'RESPOSTA':'RECUPERE DA MEMÓRIA'}</span><h2>${escapeHTML(reveal?c.flashcard.back:c.flashcard.front)}</h2>${reveal?`<p>${escapeHTML(c.summary)}</p>`:'<p>Pense na resposta antes de virar o cartão.</p>'}</div>${!reveal?button('Mostrar resposta ↻','reveal-card','','primary'):''}</div>${reveal?`<div class="rating-grid">${[['forgot','Esqueci','10 min'],['hard','Difícil','Intervalo menor'],['good','Lembrei','Revisão espaçada'],['easy','Fácil','Intervalo maior']].map(([id,t,d])=>`<button data-action="rate-card" data-id="${id}" class="rating ${id}"><strong>${t}</strong><small>${d}</small></button>`).join('')}</div>`:'<p class="footnote">A resposta só aparece quando você escolher. Sem pressa.</p>'}</div>`;}
 const due=dueConcepts(state,bank.concepts),cards=bank.concepts.filter(c=>(!cardFilters.discipline||c.discipline===cardFilters.discipline)&&(!cardFilters.status||cardFilters.status==='new'&&!state.reviews[c.id]||cardFilters.status==='due'&&isDue(state,c.id)||cardFilters.status==='favorites'&&state.favorites.includes('c:'+c.id)));
 return `${titleBlock('MEMÓRIA DE LONGO PRAZO','Recordar é aprender de novo','Vire, avalie sua lembrança e deixe a próxima revisão com o aplicativo.')}
 <section class="review-banner"><div><span class="eyebrow">SUA AGENDA</span><h2>${due.length?`${due.length} cartões esperam por você`:'Revisões em dia'}</h2><p>${due.length?'Uma retomada agora ajuda o conteúdo a permanecer.':'Você pode conhecer novos cartões ou praticar livremente.'}</p></div><button class="primary" data-action="start-cards" data-id="due" ${due.length?'':'disabled'}>Revisar pendentes →</button></section>
 <div class="section-title"><h2>Seus ${bank.concepts.length} flashcards</h2><button class="text-button" data-action="start-cards" data-id="selection" ${cards.length?'':'disabled'}>Revisar seleção →</button></div><div class="inline-filters"><label>Disciplina<select data-card-filter="discipline"><option value="">Todas as disciplinas</option>${SUBJECTS.map(s=>`<option value="${s.id}" ${cardFilters.discipline===s.id?'selected':''}>${s.name}</option>`).join('')}</select></label><label>Cartões<select data-card-filter="status"><option value="">Todos os cartões</option>${[['due','Revisões vencidas'],['new','Nunca estudados'],['favorites','Favoritos']].map(([v,t])=>`<option value="${v}" ${cardFilters.status===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="flash-grid">${cards.map(c=>`<article class="flash-preview"><div class="row"><span class="tag">${subjectById(c.discipline).name}</span>${favorite(state,'c',c.id)}</div><h3>${escapeHTML(c.flashcard.front)}</h3><div class="row"><span class="meta">${state.reviews[c.id]?relativeDue(state.reviews[c.id].dueAt):'Novo cartão'}</span>${button('Revisar →','card',c.id,'text-button')}</div></article>`).join('')||empty('Sem cartões neste filtro','Escolha outra disciplina ou situação de revisão.')}</div>`;
}
export const conceptByIdLocal = (bank,id) => bank.concepts.find(c=>c.id===id);
