import {MODE_NAMES,DIFFICULTIES,CONFIDENCE,QUESTION_TYPES} from './config.js';
import {escapeHTML,formatTime,sum} from './utils.js';
import {masteryValue} from './mastery.js';
import {subjectById,conceptById,questionById,sourceTrail,answerText,favorite,button,bar,empty,diagramSVG} from './components.js';
export function canSubmitDraft(q,draft){if(!draft?.confidence)return false;if(['choice','boolean'].includes(q.type))return Number.isInteger(draft.answer);if(q.type==='order')return draft.order?.length===q.options.length;if(q.type==='match')return draft.match?.length===q.matchLeft.length&&draft.match.every(x=>Number.isInteger(x)&&x>=0);return !!String(draft.text||'').trim();}
export function draftAnswer(q,draft){if(q.type==='order')return draft.order;if(q.type==='match')return draft.match;if(['numeric','text'].includes(q.type))return draft.text;return draft.answer;}
export function sessionScreen({state,bank,curriculum,session}){
 if(!session)return empty('Seu próximo treino está pronto','Escolha um modo para começar a praticar.','go-train','Ver modos de estudo');
 if(session.finished)return resultScreen({state,bank,session});
 const q=questionById(bank,session.currentId);if(!q)return empty('Não há mais questões nesta seleção','As respostas já foram salvas.','finish-session','Ver resultado');
 const c=conceptById(bank,q.conceptId),subject=subjectById(c.discipline),draft=session.draft||{},feedback=session.feedback,visual=diagramSVG(q.diagram);
 const indicator=session.mode==='lightning'?`<span class="session-timer" role="timer" aria-label="Tempo restante"><span aria-hidden="true">◷</span> <b id="lightning-clock">${formatTime(Math.max(0,(session.endsAt-Date.now())/1000))}</b></span>`:session.mode==='survival'?`<span class="lives" aria-label="${session.lives} ${session.lives===1?'vida restante':'vidas restantes'}">${'♥'.repeat(Math.max(0,session.lives))}<i>${'♡'.repeat(3-Math.max(0,session.lives))}</i></span>`:`<span class="question-counter">${Math.min(session.answered.length+(feedback?0:1),session.limit)} <small>/ ${session.limit}</small></span>`;
 const optionsHTML=['choice','boolean'].includes(q.type)?`<div class="answer-options ${q.type==='boolean'?'boolean-options':''}">${q.options.map((option,i)=>{const selected=feedback?feedback.answer===i:draft.answer===i;const status=feedback?(i===q.answer?'correct':selected?'incorrect':''):'';return `<button class="answer-option ${selected?'selected':''} ${status}" data-action="select-answer" data-id="${i}" aria-pressed="${selected}" ${feedback?'disabled':''}><span class="option-letter">${feedback&&i===q.answer?'✓':String.fromCharCode(65+i)}</span><span>${escapeHTML(option)}</span>${selected?'<b class="option-check">✓</b>':''}</button>`;}).join('')}</div>`:q.type==='order'?`<p class="input-hint">Use as setas para colocar os itens na ordem solicitada.</p><ol class="ordering">${(draft.order||q.options.map((_,i)=>i)).map((i,n)=>`<li><span class="order-index">${n+1}</span><span>${escapeHTML(q.options[i])}</span><div><button class="icon-button" data-action="order-up" data-id="${n}" aria-label="Mover item ${n+1} para cima" ${feedback||n===0?'disabled':''}>↑</button><button class="icon-button" data-action="order-down" data-id="${n}" aria-label="Mover item ${n+1} para baixo" ${feedback||n===q.options.length-1?'disabled':''}>↓</button></div></li>`).join('')}</ol>`:q.type==='match'?`<div class="matching">${q.matchLeft.map((left,i)=>`<label><span>${escapeHTML(left)}</span><select data-match="${i}" ${feedback?'disabled':''}><option value="">Escolha uma associação</option>${q.options.map((o,j)=>`<option value="${j}" ${draft.match?.[i]===j?'selected':''}>${escapeHTML(o)}</option>`).join('')}</select></label>`).join('')}</div>`:`<label class="answer-input-label" for="written-answer">${q.type==='numeric'?'Sua resposta numérica':'Sua resposta'}<input id="written-answer" type="text" inputmode="${q.type==='numeric'?'decimal':'text'}" maxlength="200" value="${escapeHTML(draft.text||'')}" placeholder="${q.type==='numeric'?'Digite apenas o número':'Digite uma resposta curta'}" autocomplete="off" ${feedback?'disabled':''}></label>`;
 return `<div class="session-heading"><button class="text-button" data-action="pause-session">← ${session.mode==='lightning'?'Sair do desafio':'Pausar treino'}</button><span>${MODE_NAMES[session.mode]}</span>${indicator}</div><div class="session-progress">${bar(session.answered.length/session.limit*100,'Progresso da sessão')}</div><div class="quiz-layout"><article class="question-panel"><div class="row"><div class="question-tags"><span class="tag" style="color:${subject.color}">${subject.name}</span><span class="tag difficulty d${q.difficulty}">${DIFFICULTIES[q.difficulty]}</span><span class="meta">${QUESTION_TYPES[q.type]}</span></div><span>${favorite(state,'q',q.id)}${button('⚑ Reportar','report',q.id,'text-button')}</span></div><p class="question-origin">Questão original — estilo FUVEST</p><h1 class="question-prompt">${escapeHTML(q.prompt)}</h1>${optionsHTML}
 ${visual}${!feedback?`<fieldset class="confidence-field"><legend>O quanto você confia nessa resposta?</legend><div>${Object.entries(CONFIDENCE).map(([id,label])=>`<button class="confidence-option ${draft.confidence===id?'selected':''}" data-action="confidence" data-id="${id}" aria-pressed="${draft.confidence===id}"><span>${id==='sure'?'●':id==='think'?'◐':'○'}</span>${label}</button>`).join('')}</div></fieldset><div class="answer-actions"><span class="meta" id="question-time">${formatTime(session.questionSeconds||0)} pensando</span><button class="primary" data-action="submit-answer" ${canSubmitDraft(q,draft)?'':'disabled'}>Confirmar resposta →</button></div>`:feedbackPanel(state,bank,curriculum,session,q,c)}
 ${sourceTrail(c,curriculum)}</article><aside class="quiz-aside"><article class="panel"><span class="eyebrow">NESTA SESSÃO</span><strong class="session-score">${session.score}<small> acertos</small></strong><div class="aside-line"><span>Sequência atual</span><b>${session.combo}</b></div><div class="aside-line"><span>XP conquistado</span><b>+${sum(session.answered.map(h=>h.xp))}</b></div><div class="aside-line"><span>Melhor sequência</span><b>${session.bestCombo}</b></div></article><div class="study-note"><span>✦</span><h3>A confiança também ensina</h3><p>Se estiver em dúvida, sinalize. O treino usa essa informação para retomar o conceito no momento certo.</p></div><div class="note">${session.mode==='lightning'?'O cronômetro continua mesmo ao sair da aba.':session.mode==='survival'?'Cada erro custa uma vida. A explicação fica disponível antes da próxima questão.':'Cada resposta é salva na hora. Você pode fazer uma pausa e voltar depois.'}</div></aside></div>`;
}
export function feedbackPanel(state,bank,curriculum,session,q,c){const f=session.feedback,good=f.correct,m=masteryValue(state.concepts[c.id],state.reviews[c.id]),distractor=!good&&Number.isInteger(f.answer)&&q.distractors?.[f.answer];return `<section class="feedback ${good?'feedback-correct':'feedback-wrong'}" aria-live="polite"><div class="row"><h2>${good?'✓ '+(f.confidence==='guess'?'Acertou, com uma dúvida para retomar.':'Raciocínio no caminho certo!'):f.confidence==='sure'?'Vamos corrigir um falso domínio.':'Esta é uma oportunidade de aprender.'}</h2><span class="xp-badge">+${f.xp} XP</span></div>${good&&f.confidence==='guess'?'<p>O acerto foi registrado. Sua confiança indica que precisamos testar o conceito novamente.</p>':''}${!good?`<div class="answer-comparison"><div><small>Sua resposta</small><p>${escapeHTML(answerText(q,f.answer))}</p></div><div><small>Resposta correta</small><p>${escapeHTML(answerText(q,q.answer))}</p></div></div>`:''}<div class="feedback-explanation"><div class="row"><h3>Entenda o raciocínio</h3>${favorite(state,'e',q.id)}</div><p>${escapeHTML(q.explanation)}</p>${distractor?`<p class="distractor-note">Sua alternativa: ${escapeHTML(distractor)}</p>`:''}</div><div class="feedback-bottom"><span class="meta">Domínio deste conceito: <strong>${m}%</strong> · ${good?'Progresso salvo':'Erro guardado para revisar'}</span><button class="primary" data-action="next-question">${session.answered.length>=session.limit||session.lives===0?'Ver resultado':'Próxima questão'} →</button></div></section>`;}
export function resultScreen({state,bank,session}){
 const total=session.answered.length,correct=session.score,percent=total?Math.round(correct/total*100):0,xp=sum(session.answered.map(h=>h.xp)),seconds=sum(session.answered.map(h=>h.seconds));const wrong=session.answered.filter(h=>!h.correct);
 return `<div class="result-wrap"><span class="result-symbol">✦</span><div class="eyebrow">${MODE_NAMES[session.mode].toUpperCase()} · CONCLUÍDO</div><h1>Você avançou hoje<span>.</span></h1><p>${total?'Cada resposta ajuda a escolher melhor o seu próximo passo.':'Seu progresso anterior continua salvo. Quando quiser, comece de novo.'}</p><div class="result-stats"><div><strong>${correct}<small>/${total}</small></strong><span>acertos</span></div><div><strong>+${xp}</strong><span>XP conquistado</span></div><div><strong>${percent}<small>%</small></strong><span>aproveitamento</span></div><div><strong>${formatTime(seconds)}</strong><span>tempo nas respostas</span></div></div>${['lightning','survival'].includes(session.mode)?`<div class="record-banner">Erros: <strong>${wrong.length}</strong> · Melhor sequência: <strong>${session.bestCombo}</strong> · Seu recorde no modo: <strong>${state.records[session.mode]} acertos</strong></div>`:''}<div class="result-actions">${button('Voltar à minha jornada','go-home','','primary')}${wrong.length?button('Retomar minhas dúvidas','go-errors'):button('Revisar flashcards','cards-home')}</div></div><section class="panel result-review"><div class="section-title"><h2>${wrong.length?'O que vale retomar':'Seus conceitos nesta sessão'}</h2></div>${(wrong.length?wrong:session.answered).map(h=>{const q=questionById(bank,h.questionId);return `<details><summary><span class="result-dot ${h.correct?'right':'wrong'}"></span>${escapeHTML(q.subtopic)}<span class="tag">${h.correct?'Acerto':'Retomar'}</span></summary><div><p>${escapeHTML(q.prompt)}</p><p><strong>Resposta:</strong> ${escapeHTML(answerText(q,q.answer))}</p><p>${escapeHTML(q.explanation)}</p>${button('Outra abordagem →','variation',q.conceptId,'text-button')}</div></details>`;}).join('')||'<p>Nenhuma resposta nesta sessão.</p>'}</section>`;
}
